// Ariel of the Shahnameh. Loaded inside the existing engine closure.
// campaign-data.json is transcribed from the user's design document.
const CAMPAIGN_VERSION=1, SAVE_KEY='ariel-campaign-v1', RUN_KEY='ariel-memory-v1';
const clone=v=>JSON.parse(JSON.stringify(v));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let campaign={completed:[],current:1,difficulty:'normal'}, memory=null, blessing=0, blessingMode=false, campaignActive=false;
try{const p=JSON.parse(localStorage.getItem(SAVE_KEY));if(p&&Array.isArray(p.completed))campaign={...campaign,...p,completed:p.completed.filter(n=>Number.isInteger(n)&&n>=1&&n<=62)}}catch(_){}
campaign.current=Math.max(1,Math.min(62,Number.isInteger(campaign.current)?campaign.current:1));
const currentLevel=()=>CAMPAIGN_LEVELS[(memory?.id||campaign.current)-1];
function saveProgress(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(campaign));return true}catch(_){msg('Browser storage is unavailable. Progress cannot be saved.','warn');return false}}
const stage=(kind,text,options={})=>({kind,text,...options});
const build=(type,text)=>stage('build',text||'Complete a '+type,{type});
const stock=(cost,text)=>stage('stock',text,{cost});
const fight=(label,n=1,type='stronghold')=>stage('fight','Defeat '+label,{label,n,type});
const hold=(seconds,waves,text)=>stage('hold',text,{seconds,waves});
const reach=(label,options={})=>stage('reach','Bring Ariel to '+label,{label,...options});
const escort=(label,count=1)=>stage('escort','Escort '+label+' to the refuge',{label,count});
const event=(title,text)=>stage('event',title,{body:text});
const tribute=(n,label)=>stage('tribute','Deliver '+n+' gift caravans to '+label,{n,label,cost:{gold:120,wood:40}});
const trials=names=>names.map(label=>fight(label,1,'champion'));
const PLANS={
1:[build('barracks','Build a training ground for the settlement'),stage('prepare','Expand the settlement: 8 villagers, 8 defenders and a watchtower'),stage('siamak','Send Prince Siamak to the marked northern pass'),hold(300,3,'Defend the mountain settlement: defeat all three demon waves')],
2:[stock({wood:150},'Gather wood and discover fire'),build('temple','Build the first fire temple'),build('blacksmith','Build a Blacksmith workshop'),fight("the Black Demon’s lair",1,'lair')],
3:[build('stable','Build an animal enclosure'),stage('capture','Subdue and capture seven demon chiefs alive',{n:7}),build('library','The captives teach writing: build the Library')],
4:[build('house'),build('market'),build('wonder',"Build Jamshid’s Palace"),event('The Glory departs','Jamshid claims all greatness for himself. The Glory leaves him; his own city rises against him.'),escort('the people of Jamshid',8)],
5:[build('store','Establish a hidden mountain storehouse'),stage('rescue','Help the two cooks rescue youths; grow to 40 villagers without being discovered',{n:40})],
6:[build('blacksmith','Establish Kaveh’s forge'),stock({gold:200,wood:150},'Forge Fereydun’s bull-headed mace'),event('The torn proclamation','Kaveh rejects the court’s false declaration of justice and raises his leather apron. The people follow him to Fereydun.'),fight('the Snake King’s palace'),fight('Zahhak',1,'tyrant'),reach('the cave on Mount Damavand'),event('Bound, not slain','Sorush stays Fereydun’s hand. Zahhak is chained inside Damavand; Fereydun receives the Glory.')],
7:[build('market'),tribute(2,'Salm and Tur'),event('The death of Iraj','Salm and Tur murder their brother. Ariel cannot save Iraj, but his daughter must survive.'),escort('Iraj’s daughter')],
8:[build('barracks'),fight('the two brothers’ Town Centers',2)],
9:[stock({wood:400,gold:150},'Fund the bridges and ladders to the mountain nest'),reach('Simurgh’s nest'),escort('Zal'),event('The feather','Simurgh becomes an ally. Her feather promises help in a time of need.')],
10:[build('market'),tribute(2,'Kabul'),build('observatory','Build an Observatory for the stargazers'),hold(180,3,'Protect Kabul while the marriage is approved')],
11:[build('temple'),hold(120,2,'Defend the city while the priests pray'),stock({farr:300},'Offer 300 Glory to summon Simurgh and save Rudabeh')],
12:[hold(90,2,'Delay the larger invading army'),event('Nowzar falls','The king is lost. Preserve the people who can still escape.'),escort('the villagers',8)],
13:[build('stable'),reach('the wild horse Rakhsh'),fight('the white elephant',1,'champion'),fight('the enemy camp')],
14:[build('barracks','Establish a forward base'),escort('the new king'),fight('the invading army',3,'champion')],
15:[build('barracks'),event('The White Demon’s curse','The army is blinded. Sight shrinks around your units. Rebuild your strength in the dark.'),stage('blind','Rebuild with limited vision: field 12 soldiers',{n:12})],
16:[...trials(['the lion','the desert’s raiders','the dragon','the witch','the hostile guide','the demon general','the White Demon']),escort('King Kavus')],
17:[fight('the three enemy kingdoms',3),escort('the imprisoned king')],
18:[build('nest','Build the eagle house'),stock({food:500},'Gather meat for the eagles'),event('The Whisperer’s trap','The king’s flying throne crashes into the forest. Ariel must bring him home.'),escort('King Kavus')],
19:[stock({food:500},'Provision the royal hunt'),hold(120,3,'Survive the ambush'),escort('the hunting party',5)],
20:[hold(120,2,'Defend the White Castle'),stage('duel','Witness three days of duels',{n:3}),stock({gold:300,farr:100},'Obtain the healing potion'),event('Too late','Sohrab dies before the remedy arrives. This loss is fate, not a failed mission.')],
21:[stock({wood:800},'Gather the first mountain of wood'),hold(90,2,'Protect the wood from the queen’s spies'),stock({wood:800},'Gather the second mountain of wood'),reach('the trial by fire')],
22:[build('market'),build('house'),hold(120,3,'Protect the peace treaty: defend against saboteurs'),build('wonder',"Complete Siavash’s City")],
23:[hold(90,2,'Hold the city long enough to prepare an escape'),event('The death of Siavash','Siavash is killed. His pregnant wife carries the future of the kingdom.'),escort('the pregnant princess')],
24:[build('barracks'),fight('three enemy cities',3)],
25:[build('store'),stock({food:400},'Store provisions before winter'),reach('the prince among the shepherds')],
26:[stock({wood:600},'Build rafts for the crossing'),escort('the refugees',10)],
27:[build('barracks'),stage('race','Capture the demon fortress before the rival claimant',{seconds:900,label:'the demon fortress'})],
28:[reach('Forud’s mountain castle'),event('A warning unheard','The warning comes too late. The general attacks the king’s own brother. Ariel carries the grief onward.'),escort('the survivors',4)],
29:[hold(300,5,'Hold the mountain until Rostam arrives'),fight('Kamus',1,'champion')],
30:[build('barracks'),fight('the emperor’s war elephants',6,'champion')],
31:[build('farm'),hold(120,2,'Protect the herds'),fight('the Wild Ass Demon',1,'champion')],
32:[build('market'),stock({gold:500},'Prepare a caravan of gold and jewels'),reach('the merchant entrance'),escort('Bizhan from the pit')],
33:[build('barracks'),stage('duel','Win eleven of twelve hero duels',{n:11,limit:12})],
34:[build('barracks'),build('blacksmith'),fight('the enemy capital and its fortresses',3)],
35:[build('temple','Establish a base at the holy fire'),stage('capture','Capture Afrasiyab',{n:1}),event('The king’s last journey','Afrasiyab’s reign ends. Later, Kay Khosrow walks into the snowstorm and disappears.')],
36:[fight('the giant wolf',1,'champion'),fight('the dragon',1,'champion'),escort('the princess and her guard',4)],
37:[build('temple'),stock({wood:300,farr:150},'Plant and consecrate the holy tree'),hold(300,5,'Survive the religious war')],
38:[...trials(['the wolves','the lions','the dragon','the sorceress','the monstrous bird','the snowstorm raiders','the river guard']),fight('the Brass Fortress')],
39:[stage('side','Choose a side: Rostam or Esfandiyar'),stage('duel','Fight the fated confrontation',{n:1}),event('The cost of obedience','Esfandiyar dies. Whichever side Ariel aided, the loss cannot be undone.')],
40:[reach('the hunting ground near Kabul'),event('The death of Rostam','Ariel arrives after the betrayal. Rostam has fallen.'),fight('the forces responsible in Kabul',2)],
41:[build('store'),reach('the floating cradle'),escort('the child')],
42:[build('market'),build('barracks'),fight('the usurper’s stronghold')],
43:[hold(240,4,'Delay Alexander’s advance'),escort('the people of Dara',10)],
44:[build('wonder','Build the Great Iron Wall'),reach('the search for the Water of Life'),event('Beyond conquest','The journey teaches the limits of kingship. The Water of Life remains beyond Alexander’s grasp.')],
45:[escort('Ardashir’s followers',5),build('barracks'),fight('the old king')],
46:[stock({gold:500,wood:300},'Prepare the metal and furnace for molten lead'),reach('the merchant disguise rendezvous'),reach('the Giant Worm’s enclosure')],
47:[build('barracks'),fight('the Roman Emperor’s army',3,'champion')],
48:[stage('tax','Keep 12 villagers alive under crushing taxes until the mysterious horse comes',{seconds:300,n:12}),event('The cruel king falls','A mysterious horse kills the king. The people outlast his rule.')],
49:[build('barracks'),fight('the two lions',2,'champion'),reach('the crown')],
50:[build('market'),build('farm'),tribute(3,'the musicians from India'),stock({food:500,gold:300},'Hold a festival for the people')],
51:[build('barracks'),stage('ambush','Gather 12 soldiers behind the town before springing the night attack',{n:12}),fight('the unsuspecting enemy camp')],
52:[hold(180,3,'Preserve the people through Piruz’s defeat'),event('The general returns','After the defeat, the general rebuilds the army for revenge.'),fight('the enemy’s stronghold')],
53:[build('store','Build the granaries'),stage('famine','Survive famine and unrest with at least 12 villagers',{seconds:300,n:12})],
54:[build('wonder','Build the Great Palace Arch'),stage('puzzle','Solve the minister’s chess challenge and explain backgammon')],
55:[build('blacksmith'),hold(180,4,'Defend several fronts'),fight('the opposing fortresses',3)],
56:[build('tower'),hold(360,6,'Hold the narrow approaches against the larger army')],
57:[event('The Whisperer divides the court','The general rebels and the kingdom splits. Ariel must hold a place of refuge.'),hold(180,3,'Survive the first blows of civil war'),fight('the rebel stronghold')],
58:[build('market'),tribute(3,'the Roman alliance'),fight('the usurper’s capital')],
59:[build('wonder','Establish the palace court'),stage('court','Earn court favor while resisting the Whisperer’s plots',{n:5})],
60:[event('The Glory fades','Ariel’s strength begins to leave him as the prince turns against his father.'),hold(300,5,'Survive the prince’s coup while Ariel weakens')],
61:[stage('succession','Keep the kingdom alive through five changes of ruler',{seconds:600,n:5})],
62:[hold(420,7,'Preserve the last refuge through the final defence'),event('The last king','Yazdegerd III dies. The Glory leaves Iran and Ariel becomes mortal. Sorush carries mortal Ariel forward to Tus, where he will tell Ferdowsi what he witnessed. The kingdom’s fall is the story’s ending, not a retry screen.')]
};

// New definitions retain the rendering and pathfinding of the existing RTS.
function define(type,base,props){DEF[type]={...clone(DEF[base]),...props};BASE_DEF[type]=clone(DEF[type]);SHORT[type]=DEF[type].name;IC[type]=IC[base]||IC.temple}
define('ariel','fereydun',{name:'Ariel · Guardian of the Glory',hp:550,atk:16,regen:2,desc:'Immortal guardian. Bless one building to make it work 20% faster. The blessing can be moved.',hero:1});
define('companion','spearman',{name:'Story companion',hero:1,hp:500,atk:22,pop:0,cost:undefined,desc:'A hero of this memory. Ariel protects the people; he cannot change fate.'});
define('priest','villager',{name:'Priest',cls:'priest',atk:0,cost:{food:80,gold:30},time:14,desc:'Prays beside a completed Temple to generate 0.6 Glory per second.'});
define('caravan','horseman',{name:'Trade Caravan',cls:'trade',atk:0,hp:160,cost:{wood:80,gold:50},time:18,desc:'Travels between your Market and a distant trade post to earn gold.'});
define('ram','horseman',{name:'Siege Ram',hp:650,atk:30,rof:2,spd:26,age:3,cls:'siege',bonus:{bld:5},cost:{wood:200,gold:130},time:30,desc:'Slow siege weapon. Strong against buildings.'});
define('dragon','simurgh',{name:'Dragon',age:4,heal:0,atk:32,hp:700,cost:{gold:250,farr:80},pop:6,desc:'A flying myth unit unlocked in the Age of Myth.'});
define('cave','store',{name:'Mountain Cave',trains:['villager','spearman'],popc:25,hp:2200,cost:undefined,desc:'Shelter for Kayumars’s mountain people. Gather berries and hunt; train villagers and stone-armed defenders.'});
define('range','barracks',{name:'Archery Range',age:2,trains:['archer'],desc:'Trains archers.'});
define('blacksmith','store',{name:'Blacksmith',age:2,w:3,h:3,cost:{wood:150,gold:80},time:28,desc:'Research weapons and armor.'});
define('market','stable',{name:'Market',age:2,trains:['caravan'],cost:{wood:180,gold:80},desc:'Exchange resources and train trade caravans.'});
define('library','temple',{name:'Library',age:2,farr:0,trains:[],desc:'Preserves the writing taught by the captured demons.'});
define('observatory','tower',{name:'Observatory',age:2,atk:0,cost:{wood:200,gold:200},desc:'A place for stargazers to study the heavens.'});
define('nest','temple',{name:'Simurgh’s Nest',age:3,trains:['simurgh','dragon'],farr:0,cost:{wood:200,gold:150},desc:'Calls mythic flying allies.'});
define('wonder','palace',{name:'Wonder',age:3,atk:0,cost:{wood:900,gold:700},time:150,hp:6000,desc:'A monumental building unique to the current story.'});
define('wall','store',{name:'Wall',w:1,h:1,drop:0,hp:1400,cost:{wood:30,gold:10},time:9,desc:'Build a straight line by clicking its start and end. Select a finished section to add a gate.'});
define('gate','wall',{name:'Friendly Gate',hp:1400,cost:{wood:45,gold:20},time:12,desc:'Your units pass through this gate. Enemies must break it down.'});
define('stronghold','palace',{name:'Enemy Stronghold',hp:2200,atk:5});
define('lair','pit',{name:'Black Demon’s Lair',hp:1800});
define('champion','div',{name:'Enemy Champion',hp:600,atk:20});
define('tyrant','zahhak',{name:'Zahhak',hp:2200});
define('tradepost','store',{name:'Trade Post',invul:1,drop:0,desc:'Destination for market caravans.'});
const bAliases={cave:'store',range:'barracks',blacksmith:'store',market:'stable',library:'temple',observatory:'tower',nest:'temple',wonder:'palace',wall:'store',gate:'wall',stronghold:'palace',lair:'pit',tradepost:'store'};
for(const [t,a] of Object.entries(bAliases))BUILD[t]=BUILD[a];
const originalHumanSpec=humanSpec, originalUnitModel=unitModel, originalAnimUnit=animUnit;
humanSpec=function(type,team){if(type==='ariel')return{tunic:0x183f53,trim:0xdfb656,pants:0x252b36,hair:0x211b16,beard:0x302017,cape:0x285668,skin:0xb58260,heroTrim:1,tools:['w_sword'],wk:'sword',scale:1.13};if(type==='companion')return{...originalHumanSpec('spearman',team),regalia:0,referenceSoldier:0,cape:0x7c3535,heroTrim:1,scale:1.15};if(type==='priest')return{tunic:0xe5dbc3,trim:0xc9a65d,pants:0x918265,hat:'hood',hatc:0xe5dbc3,beard:0x797064,tools:[],scale:1};return originalHumanSpec(type,team)};
const uAliases={caravan:'horseman',ram:'horseman',dragon:'simurgh',champion:'div',tyrant:'zahhak'};
unitModel=function(type,team){return originalUnitModel(uAliases[type]||type,team)};
animUnit=function(R,e,t,dt){return originalAnimUnit(R,uAliases[e.type]?{...e,type:uAliases[e.type]}:e,t,dt)};
Object.assign(AGES,{1:'Age of Fire',2:'Age of Iron',3:'Age of Heroes',4:'Age of Myth'});
Object.assign(DEF.archer,{age:2});Object.assign(DEF.simurgh,{age:3});Object.assign(DEF.barracks,{trains:['spearman'],desc:'Trains infantry.'});
Object.assign(DEF.temple,{farr:0,trains:['priest'],desc:'Train priests. Priests beside a Temple pray to generate Glory.'});
DEF.tc.cost={wood:400,gold:200};DEF.tc.time=60;
for(const t of ['archer','simurgh','barracks','temple','tc'])BASE_DEF[t]=clone(DEF[t]);
BUILDS.splice(0,BUILDS.length,'house','store','farm','barracks','temple','range','stable','blacksmith','market','wall','tower','nest','wonder','library','observatory');
for(const k of ['spearheads','armour','bows','veteran','champion'])TECH[k].at='blacksmith';
TECH.flame.eff='Priests generate Glory twice as fast.';TECH.flame.apply=()=>{memory.prayerMultiplier=2};
AGE_STEPS[2].requires=['temple'];AGE_STEPS[2].bonus='Unlock the Blacksmith, archers, cavalry and your first patron power.';
AGE_STEPS[3].requires=['temple','blacksmith'];AGE_STEPS[3].bonus='Unlock siege weapons, Simurgh’s Nest and advanced research.';
AGE_STEPS[4].requires=['temple','nest'];AGE_STEPS[4].bonus='Unlock dragons, demons and the strongest patron powers.';
DEF.blacksmith.trains=['ram'];BASE_DEF.blacksmith=clone(DEF.blacksmith);
const PATRONS={2:[['rain','God of Rain','Farms produce 25% more food.','anahita'],['justice','God of Justice','Infantry gain 20% attack.','mithra'],['fortune','Goddess of Fortune','Gold gathering is 25% faster.','ahura']],3:[['messages','God of Messages','Reveal enemy strongholds.','ahura'],['wind','God of Wind','Cavalry move 25% faster.','mithra'],['healing','God of Healing','All units recover slowly outside combat.','anahita']],4:[['simurgh','The Simurgh','A Simurgh joins your army.','anahita'],['victory','God of Victory','All soldiers gain 25% attack.','mithra'],['water','Goddess of Water','Farms produce another 40% more food.','anahita']]};
function applyPatron(id){if(id==='rain')RATE.farm*=1.25;if(id==='justice')DEF.spearman.atk*=1.2;if(id==='fortune')RATE.mine*=1.25;if(id==='wind')DEF.horseman.spd*=1.25;if(id==='water')RATE.farm*=1.4;if(id==='victory')for(const t of ['spearman','archer','horseman','ram'])DEF[t].atk*=1.25;if(id==='healing')memory.healing=true;if(id==='messages'){reveals.push({x:64,y:14,r:22,until:now+3600})}}
const originalAgeRequirement=ageRequirement;
ageRequirement=function(){if(age>=currentLevel().maxAge)return 'This memory ends at '+AGES[currentLevel().maxAge]+'.';return originalAgeRequirement()};
doAgeUp=function(){if(age>=currentLevel().maxAge||age>=4)return;age++;memory.pendingPatron=age;cmdSig='';sfx('fanfare');choosePatron()};
function choosePatron(){const a=memory.pendingPatron;const options=PATRONS[a].map(([id,name,desc,power])=>({t:name+' — '+desc,f:()=>{applyPatron(id);memory.patrons.push(id);powers.push({k:power,used:false});if(id==='simurgh')spawnAlly('simurgh');memory.pendingPatron=0;closeModal();refreshPowers();saveMemory(false)}}));showMemoryCard('Choose your patron',AGES[a],'<p>'+esc(AGE_STEPS[a].bonus)+'</p>',options);if(a!==2)return;$('#modal').classList.add('patron-modal');const art=$('#story-visual'),img=$('#story-art');art.hidden=false;img.hidden=false;img.src='assets/age-of-iron-forge.png';img.alt='An ancient mountain forge at dawn, with a blacksmith working iron beside a fire temple';$('#story-caption').hidden=false;$('#story-caption').textContent='The first forge is lit. Choose the blessing that will guide this age.';$('#m-text').innerHTML='<p>Iron is ready to work. Choose one lasting blessing for your settlement.</p>';$('#m-acts').querySelectorAll('button').forEach((button,i)=>{const [,name,desc]=PATRONS[a][i];button.className='patron-choice';button.innerHTML='<span class="patron-number">0'+(i+1)+'</span><span class="patron-copy"><strong>'+esc(name)+'</strong><small>'+esc(desc)+'</small></span><span class="patron-arrow" aria-hidden="true">›</span>'})}
function spawnAlly(type,n=1){const b=ents.find(e=>e.team===0&&e.kind==='bld'&&alive(e));for(let i=0;i<n;i++){const p=b?spawnSpot(b):{x:14*TILE,y:67*TILE};mkUnit(type,0,p.x+i*12,p.y)}recalcPop()}
function available(type){const id=currentLevel().id;if(id===1)return ['villager','spearman','house','store','farm','barracks','tower','wall'].includes(type);if(id===2&&['market','range','nest','wonder','observatory','library'].includes(type))return false;if(id===3&&['wonder','observatory'].includes(type))return false;if(type==='library'&&id===3&&!memory.writing)return false;return age>=(DEF[type]?.age||1)}

// All opening, mid-mission and ending prose uses the new narrator frame.
function showMemoryCard(title,eyebrow,text,actions){paused=true;$('#modal').hidden=false;cancelAnimationFrame(sceneAnim);menuOpen=false;$('#modal').classList.remove('patron-modal');$('#modal').classList.add('memory-modal');$('#story-visual').hidden=true;$('#m-eb').textContent=eyebrow;$('#m-title').textContent=title;$('#m-text').innerHTML=text;$('#m-acts').replaceChildren();for(const a of actions||[{t:'Continue',f:closeModal}]){const b=document.createElement('button');b.className='big';b.textContent=a.t;b.onclick=a.f;$('#m-acts').append(b)}}
function memoryIntro(){const l=currentLevel();showMemoryCard(l.title,l.act+' · Memory '+l.id+' of 62','<p class="narrator">Tus, about the year 1000 · Ariel speaks to Ferdowsi</p><blockquote>“I was there. Let me tell you.”</blockquote>'+(l.id===1?'<p>Kayumars led our mountain settlement. His son, Prince Siamak, commanded its defenders; I was an orphan who helped build the refuge. Scouts had seen a Black Demon beyond the northern pass. We had time to prepare, but we knew an attack would come.</p><p>Build a training ground, grow the village and raise its defences. When the scout returns, you will lead Siamak to the pass.</p>':l.id===2?'<p>After Siamak fell, Hushang sought a way to strengthen our people. Fire came first. Iron would follow. I stayed to help his settlement learn both crafts.</p><p>Build a Fire Temple, gather gold, advance at the Town Center to the Age of Iron, then build a Blacksmith workshop with a villager.</p>':'<p>I carried the Glory through another generation. The Whisperer changed his face, but not his purpose. I could help the living; I could not undo their fate.</p>')+'<p>'+esc(l.economy)+'</p><p><b>Your mission:</b> '+esc(l.mission)+'</p><p class="ctl">Maximum: '+AGES[l.maxAge]+'. Ariel and the Whisperer are original connecting characters in this adaptation.</p>',[{t:'Begin memory',f:()=>{closeModal();beginStage()}},{t:'Campaign',f:openCampaign}])}
function openCampaign(){paused=true;$('#modal').hidden=true;cancelAnimationFrame(sceneAnim);$('#campaign').hidden=false;renderCampaign(campaign.current);}
function renderCampaign(selected){const l=CAMPAIGN_LEVELS[selected-1];$('#campaign-list').innerHTML=[...new Set(CAMPAIGN_LEVELS.map(x=>x.act))].map(act=>'<h3>'+esc(act)+'</h3>'+CAMPAIGN_LEVELS.filter(x=>x.act===act).map(x=>'<button class="memory-entry '+(x.id===selected?'selected':'')+'" data-level="'+x.id+'"><span>'+String(x.id).padStart(2,'0')+'</span><b>'+esc(x.title)+'</b><small>'+(campaign.completed.includes(x.id)?'Completed':canStart(x.id)?'Available':'Locked')+'</small></button>').join('')).join('');$('#campaign-detail').innerHTML='<p class="ey">'+esc(l.act)+' · Memory '+l.id+'</p><h2>'+esc(l.title)+'</h2><p>'+esc(l.economy)+'</p><h3>The mission</h3><p>'+esc(l.mission)+'</p><p class="ctl">Age limit: '+AGES[l.maxAge]+' · '+PLANS[l.id].filter(s=>s.kind!=='event').length+' objectives</p><button class="big" id="start-memory" '+(!canStart(l.id)?'disabled':'')+'>'+(campaign.completed.includes(l.id)?'Replay memory':'Begin memory')+'</button>'+(!canStart(l.id)?'<p class="ctl">Complete memory '+(l.id-1)+' to unlock this story.</p>':'');$('#start-memory').onclick=()=>startMemory(l.id);$('#campaign-progress').textContent=campaign.completed.length+' / 62 memories completed';$('#resume-memory').hidden=!readSave();$('#return-memory').hidden=!campaignActive||gameOver;$('#campaign-list').querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>renderCampaign(+b.dataset.level));}
// Development switch: every memory can be started without finishing the previous one.
// Set to false before a public release to restore normal story progression.
const DEV_UNLOCK_ALL=true;
function canStart(id){return DEV_UNLOCK_ALL||id===1||campaign.completed.includes(id)||campaign.completed.includes(id-1)}
let renderedLandscape=1,staticWorld=[],landscapeBusy=false;
const originalBuildWorld3D=buildWorld3D;
buildWorld3D=function(){const before=new Set(scene.children);try{originalBuildWorld3D();renderedLandscape=LANDSCAPE_SEED}finally{staticWorld=scene.children.filter(child=>!before.has(child))}};
function clearLandscape3D(){const seen=new Set();for(const child of staticWorld)disposeVisual(child,seen);staticWorld=[];CHUNKS.length=0;scatIM.length=0;scatByTile.clear();treeIM={};rallyObj=null;scene.userData.sky=null;renderedLandscape=0}
function setRiverForMemory(id){if(id===1){RIV.splice(0,RIV.length,[24,-3],[27,12],[35,28],[50,39],[66,43.5],[83,47]);return}const rand=mulberry32(8303+id*733),bend=()=>rand()*8-4;RIV.splice(0,RIV.length,[24+bend(),-3],[27+bend(),12],[31,20],[35+bend(),28],[43.25,34.05],[50+bend(),39],[59.6,41.7],[66+bend(),43.5],[74.5,45.25],[83,47+bend()])}
async function prepareLandscape(id){if(renderedLandscape===id)return;$('#loading').hidden=false;$('#lmsg').textContent='Shaping the landscape for '+CAMPAIGN_LEVELS[id-1].title+'…';$('#lbar').style.width='0%';clearWorld3D();clearLandscape3D();LANDSCAPE_SEED=id;setRiverForMemory(id);originalMiniMap=null;try{await genWorldData(p=>{$('#lbar').style.width=(p*100)+'%'});buildWorld3D()}catch(err){clearLandscape3D();throw err}$('#loading').hidden=true}
async function startMemory(id){if(!canStart(id)||landscapeBusy)return;landscapeBusy=true;$('#campaign').hidden=true;campaign.current=id;saveProgress();memory={id,stage:0,stageAt:0,started:false,targets:[],patrons:[],wave:0,kills:0,deliveries:0,duels:0,blessing:0,prayerMultiplier:1};campaignActive=true;try{await prepareLandscape(id);setupWorld();memoryIntro();saveMemory(false)}catch(err){console.error(err);$('#loading').hidden=true;showMemoryCard('Map could not load','Please retry','<p>The landscape could not be prepared. Try beginning this memory again.</p>',[{t:'Campaign',f:openCampaign}])}finally{landscapeBusy=false}}

// Every memory has a reproducible terrain signature. The nine acts set the broad
// biome, while the memory number changes its tint, tree cover and landform layout.
const LANDSCAPE_LOOKS=[
  {tone:[.96,1.02,1.08],trees:.78,forms:['ridge','snowcrest']},
  {tone:[1.08,.99,.85],trees:.52,forms:['mesa','stonefield']},
  {tone:[1.11,.91,.78],trees:.37,forms:['mesa','ridge']},
  {tone:[.87,1.08,.88],trees:.9,forms:['copse','ridge']},
  {tone:[.97,.92,.86],trees:.49,forms:['stonefield','mesa']},
  {tone:[.9,.98,1.12],trees:.65,forms:['snowcrest','ridge']},
  {tone:[.92,1.07,1.01],trees:.86,forms:['copse','stonefield']},
  {tone:[.87,.91,1.01],trees:.56,forms:['ridge','stonefield']},
  {tone:[1.03,1.05,.88],trees:.72,forms:['copse','mesa']}
];
const ACT_NAMES=[...new Set(CAMPAIGN_LEVELS.map(l=>l.act))];
const LANDSCAPE_TYPES=new Set(['ridge','mesa','copse','stonefield','snowcrest']);
let originalMiniMap=null;
function landscapeLook(id){return LANDSCAPE_LOOKS[Math.max(0,ACT_NAMES.indexOf(CAMPAIGN_LEVELS[id-1].act))]}
function applyLandscape(id){
  const look=landscapeLook(id),tone=look.tone,variation=.94+hash2(id,47)*.12;
  for(const mesh of scene.children){const geo=mesh.geometry,colors=geo?.attributes?.tint,positions=geo?.attributes?.position;if(!colors||!geo.attributes.splat||!positions)continue;
    for(let i=0;i<colors.count;i++){const x=positions.getX(i),z=positions.getZ(i),ix=clamp(Math.round((x-HOFF)*HR),0,HN-1),iz=clamp(Math.round((z-HOFF)*HR),0,HN-1),k=(iz*HN+ix)*3;const local=.97+.03*Math.sin(x*.23+id*1.7)*Math.cos(z*.19-id*.8);colors.setXYZ(i,TINT[k]*tone[0]*variation*local,TINT[k+1]*tone[1]*variation*local,TINT[k+2]*tone[2]*variation*local)}colors.needsUpdate=true;
  }
  const ctx=miniBase.getContext('2d');if(!originalMiniMap)originalMiniMap=new Uint8ClampedArray(ctx.getImageData(0,0,160,160).data);const im=ctx.createImageData(160,160);for(let i=0;i<im.data.length;i+=4){im.data[i]=Math.min(255,originalMiniMap[i]*tone[0]*variation);im.data[i+1]=Math.min(255,originalMiniMap[i+1]*tone[1]*variation);im.data[i+2]=Math.min(255,originalMiniMap[i+2]*tone[2]*variation);im.data[i+3]=255}ctx.putImageData(im,0,0);
}
function addLandscapeForms(id){if(id===1)return;const look=landscapeLook(id),rand=mulberry32(9191+id*883),count=7+id%5;let placed=0;
  for(let attempt=0;attempt<450&&placed<count;attempt++){const x=5+Math.floor(rand()*68),y=8+Math.floor(rand()*61),cx=x+1.5,cy=y+1.5;if(Math.hypot(cx-14,cy-65)<11||targetSites.some(p=>Math.hypot(cx-p[0],cy-p[1])<7)||MAP_PATHS.some(p=>segD(cx,cy,...p)<3.6))continue;if(!fits(x,y,3,3))continue;const type=look.forms[Math.floor(rand()*look.forms.length)];mkBld(type,2,x,y,true);placed++}
  memory.landscapeForms=placed;
}

setupWorld=function(){resetStats();clearWorld3D();ents=[];byId.clear();nextId=1;projs=[];fxs=[];pings=[];reveals=[];blocked.set(tblk);occ.fill(0);vis.fill(0);expl.fill(0);res={food:250,wood:250,gold:150,farr:0};age=1;now=0;gameOver=false;flags={};powers=[];sel=[];placing=null;wallStart=null;targeting=null;blessing=0;blessingMode=false;aiT=trigT=fogT=0;palaceDown=false;zahhakSpawned=false;const l=currentLevel();applyLandscape(l.id);
  if(l.id===1){memory.settlementRevision=3;res={food:600,wood:650,gold:0,farr:0};DEF.tower.cost={wood:120};DEF.tower.name='Mountain Watchtower';DEF.barracks.trains=['spearman'];DEF.barracks.name='Training Ground';DEF.wall.cost={wood:25};DEF.gate.cost={wood:45};DEF.farm.age=1;DEF.spearman.name='Stone Defender';DEF.spearman.cost={food:60};DEF.spearman.atk=7;DEF.serpent.atk=5;DEF.champion.name='The Black Demon';DEF.villager.desc='Builds the settlement, gathers wood and food, and farms. Train more villagers at the cave.';DEF.companion.name='Prince Siamak';DEF.companion.desc='Kayumars’s son. Lead him to the marked pass when the Black Demon is sighted.';}
  if(l.id>1){const growth=1+(l.id-2)*.0075;for(const t of ['serpent','bowman','champion','tyrant']){DEF[t].hp=Math.round(DEF[t].hp*growth);DEF[t].atk*=growth;}}
  DEF.wonder.name=({4:'Jamshid’s Palace',22:'Siavash’s City',44:'Great Iron Wall',54:'Great Palace Arch',59:'Royal Palace'})[l.id]||'Wonder';
  if(l.id===1)for(const [x,y] of [[6,54],[0,46],[16,46],[32,38],[48,30],[64,22],[0,30],[16,22]])mkBld('mountain',2,x,y,true);
  const home=mkBld(l.id===1?'cave':'tc',0,12,62,true);for(let i=0;i<(l.id===1?5:6);i++)mkUnit('villager',0,(12+i*.9)*TILE,67*TILE);mkUnit('ariel',0,17*TILE,66.5*TILE);for(let i=0;i<(l.id===1?6:3);i++)mkUnit('spearman',0,(12+i)*TILE,69*TILE);
  if(l.id===1){mkBld('house',0,7,65,true);mkBld('house',0,9,69,true);mkBld('store',0,18,63,true);mkBld('farm',0,21,63,true);}
  if(l.id===1)mkUnit('companion',0,18*TILE,67*TILE);else if(l.id===6){mkUnit('kaveh',0,18*TILE,67*TILE);mkUnit('fereydun',0,19*TILE,67*TILE)}else if(l.id>6){DEF.companion.name=l.id<=8?'Manuchehr':l.id<=11?'Zal':l.id<=35?'Rostam':l.id<=39?'Esfandiyar':'Royal champion';mkUnit('companion',0,18*TILE,67*TILE)}
  for(const p of [[20,67],[21,68],[22,67],[20,69],[22,69],[21,70],[9,58],[10,58],[8,57],[37,61],[38,62],[36,62],[37,63]])placeFree('bush',2,...p);
  if(l.id!==1)for(const p of [[23,57],[7,71],[40,52],[49,66],[29,74],[50,24],[70,32],[33,44]])placeFree('mine',2,...p);
  for(const p of [[8,65],[20,74],[9,72]]){const r=placeFree('bush',2,...p);if(r)r.amt=1000}
  const post=placeFree('tradepost',2,38,60,true);if(post)memory.tradepost=post.id;
  addLandscapeForms(l.id);
  TREES.forEach((t,k)=>{const i=t.ty*MW+t.tx;if(occ[i]||blocked[i]||(l.id>1&&hash2(t.tx+l.id*13,t.ty+l.id*31)>landscapeLook(l.id).trees)){hideTree(k);return}const e=mkRes('tree',t.tx,t.ty);e.ti=k});
  OBJ=[];cam.z0=l.id===1?29:Math.min(innerWidth,innerHeight)<520?14:22;centerOn(home.x,home.y);recalcPop();updateFog();portCache.clear();selSig=cmdSig=objSig='';refreshPowers();refreshSel();refreshObj();$('#obj').classList.remove('min');$('#objh span').textContent='hide';};

const targetSites=[[36,61],[48,58],[48,44],[60,38],[46,28],[58,21],[65,12]];
function missionPoint(index=0){const p=targetSites[Math.min(6,index)];const f=nearFree(p[0],p[1]);return f?{x:f.x*TILE+16,y:f.y*TILE+16}:{x:p[0]*TILE,y:p[1]*TILE}}
function stageTarget(type,team,index){const p=targetSites[Math.min(6,index)];for(const e of ents)if(e.kind==='res'&&Math.hypot(e.tx-p[0],e.ty-p[1])<6){e.dead=true;stampE(e,false);resGone(e)}buildGrid();const d=DEF[type];return d.kind==='bld'?placeFree(type,team,p[0],p[1],true):mkUnit(type,team,missionPoint(index).x,missionPoint(index).y)}
function beginStage(){if(!memory||gameOver)return;const s=PLANS[memory.id][memory.stage];if(!s){finishMemory();return}memory.started=true;memory.stageAt=now;memory.targets=[];memory.wave=0;memory.deliveries=0;memory.duels=0;memory.goal=0;memory.marker=null;memory.actionReady=false;memory.drainTick=0;saveMemory(false);
  if(s.kind==='siamak'){let prince=ents.find(e=>e.type==='companion'&&e.team===0&&alive(e));if(!prince){const home=ents.find(e=>e.type==='cave'&&e.team===0);const p=home?spawnSpot(home):{x:18*TILE,y:67*TILE};prince=mkUnit('companion',0,p.x,p.y)}memory.siamakId=prince.id;memory.duelStarted=false;memory.duelResolved=false;memory.marker=missionPoint(0);updateFog();refreshMissionHUD();saveMemory(false);showMemoryCard('The scout returns','Kayumars · the northern pass','<p>The Black Demon has crossed the northern ridge. Prince Siamak, Kayumars’s son and captain of your defenders, goes to meet it before it reaches the village.</p><p><b>What to do:</b> Select Prince Siamak and send him to the gold mission marker at the pass. The village remains yours to defend.</p>',[{t:'Find Prince Siamak',f:()=>{closeModal();setSel([prince.id]);centerOn(prince.x,prince.y)}}]);return}
  if(s.kind==='event'){if(['The death of Siamak','The death of Iraj','The death of Siavash','Nowzar falls','The last king','The cost of obedience'].includes(s.text)){for(const e of ents)if(e.type==='companion'&&e.team===0){e.dead=true;e.fallen=false}}saveMemory(false);showMemoryCard(s.text,'Ariel remembers','<p>'+esc(s.body)+'</p>',[{t:'Continue the memory',f:()=>{closeModal();advanceStage()}}]);return}
  if(s.kind==='fight'||s.kind==='race'){for(let i=0;i<(s.n||1);i++){const e=stageTarget(s.type||'stronghold',1,Math.min(6,1+i+memory.stage%3));if(e){e.guard=1;e.hx=e.x;e.hy=e.y;memory.targets.push(e.id);for(let j=0;j<3;j++)mkUnit('serpent',1,e.x+(j-1)*24,e.y+100,{guard:1,hx:e.x,hy:e.y+100})}}}
  if(s.kind==='capture'){for(let i=0;i<s.n;i++){const e=stageTarget('champion',1,i%7);e.hp=300;e.captureChief=true;e.guard=1;e.hx=e.x;e.hy=e.y;memory.targets.push(e.id)}}
  if(['reach','escort','tribute'].includes(s.kind)){memory.marker=missionPoint(memory.stage%3);if(s.kind==='escort'){for(let i=0;i<s.count;i++){const e=mkUnit('villager',2,memory.marker.x+i*18,memory.marker.y);e.escort=true;memory.targets.push(e.id)}memory.escorting=false}}
  if(s.kind==='rescue'){memory.rescueAt=now+25;memory.detection=0}
  if(s.kind==='blind')memory.blind=true;
  if(s.kind==='famine')res.food=0;
  if(s.kind==='duel')spawnDuel();
  if(s.kind==='side'){showMemoryCard('Rostam or Esfandiyar?','A divided loyalty','<p>Ariel may choose whom to aid, but cannot change Esfandiyar’s fate.</p>',[{t:'Aid Rostam',f:()=>{memory.side='Rostam';closeModal();advanceStage()}},{t:'Aid Esfandiyar',f:()=>{memory.side='Esfandiyar';closeModal();advanceStage()}}]);return}
  if(memory.targets.length){const e=byId.get(memory.targets[0]);if(e)memory.marker={x:e.x,y:e.y}}
  OBJ=PLANS[memory.id].filter(x=>x.kind!=='event').map((x,i)=>({id:'memory-'+i,text:x.text,done:PLANS[memory.id].indexOf(x)<memory.stage,hidden:PLANS[memory.id].indexOf(x)>memory.stage}));refreshObj();saveMemory(false);}
function advanceStage(){memory.stage++;memory.started=false;beginStage()}
function showSiamakAftermath(){showMemoryCard('Siamak falls at the pass','What happened · what comes next','<p>You sent Prince Siamak to hold the northern pass. He met the Black Demon there and fell in the fight. The demon withdrew, but its army is coming for Kayumars’s settlement.</p><p>Sorush now calls Ariel to guard the Glory of the Kings. Ariel cannot undo Siamak’s death; he can help protect the people Siamak fought for.</p><p><b>Next:</b> Return to your village. Train defenders, repair your buildings and survive three small demon attacks.</p>',[{t:'Return and defend the village',f:()=>{closeModal();advanceStage();const home=ents.find(e=>e.type==='cave'&&e.team===0&&alive(e));if(home)centerOn(home.x,home.y)}}])}
function spawnDuel(){const s=PLANS[memory.id][memory.stage];const e=stageTarget('champion',1,0);e.hp=200+memory.duels*20;e.duelist=true;e.guard=1;e.hx=e.x;e.hy=e.y;memory.targets=[e.id];memory.marker={x:e.x,y:e.y};}
function finishMemory(){gameOver=true;paused=true;if(!campaign.completed.includes(memory.id))campaign.completed.push(memory.id);campaign.current=Math.min(62,memory.id+1);saveProgress();try{localStorage.removeItem(RUN_KEY)}catch(_){}const last=memory.id===62;showMemoryCard(last?'The story survives':'A memory preserved','Tus · Ariel and Ferdowsi',last?'<p>Ariel finishes his account. Sorush has carried him across the centuries to this meeting. His immortality has ended, but Ferdowsi promises that the stories will live in his poem. The Glory the Whisperer sought survives in memory.</p>':'<p>'+esc(currentLevel().mission)+'</p><p>Ferdowsi sets down this memory. Ariel turns to the next generation.</p>',[{t:last?'Return to the chronicle':'Next memory',f:last?openCampaign:()=>startMemory(memory.id+1)},{t:'Campaign',f:openCampaign}]);}
defeat=function(){if(gameOver)return;gameOver=true;paused=true;showMemoryCard('The memory is unfinished','Retry this mission','<p>The refuge has fallen or the people needed for this mission have been lost. The scripted tragedies are part of the story; this defeat can be retried.</p>',[{t:'Retry memory',f:()=>startMemory(memory.id)},{t:'Campaign',f:openCampaign}])};
restart=()=>startMemory(memory?.id||campaign.current);
onPalaceDown=()=>{};onZahhakDown=()=>{};

function launchMemoryWave(n){const home=ents.find(e=>e.team===0&&['tc','cave'].includes(e.type)&&alive(e));if(!home)return;const p=missionPoint(n%2);const count=memory.id===1?[3,5,7][n]:Math.min(20,4+n+Math.floor((memory.id-2)/6)+(campaign.difficulty==='hard'?3:0));for(let i=0;i<count;i++){const e=mkUnit(memory.id===1?'serpent':i%4===3?'bowman':'serpent',1,p.x+i*20,p.y);e.memoryWave=true;if(memory.id===1){e.hp=60+n*15;}orderMove(e,home.x,home.y,true)}msg('Enemy wave '+(n+1)+' approaches.','warn')}
aiTick=function(){if(!campaignActive||!memory||gameOver)return;for(const e of ents)if(e.fallen&&now>=e.respawnAt){const home=ents.find(b=>b.team===0&&['tc','cave'].includes(b.type)&&alive(b));if(home){const p=spawnSpot(home);Object.assign(e,{x:p.x,y:p.y,fallen:false,hp:DEF[e.type].hp,state:'idle'});msg(DEF[e.type].name+' returns to the refuge.','good')}}};
triggers=function(){if(!campaignActive||!memory||gameOver||!memory.started||paused)return;const s=PLANS[memory.id][memory.stage];if(!s||s.kind==='event'||s.kind==='side')return;const elapsed=now-memory.stageAt,has=t=>ents.some(e=>e.type===t&&e.team===0&&e.done&&alive(e));const people=ents.filter(e=>e.type==='villager'&&e.team===0&&alive(e));const ariel=ents.find(e=>e.type==='ariel'&&alive(e));const army=ents.filter(e=>e.team===0&&alive(e)&&['inf','arc','cav','siege'].includes(DEF[e.type].cls));let done=false;
  if(s.kind==='siamak'){const prince=byId.get(memory.siamakId);if(!memory.duelStarted&&prince&&memory.marker&&Math.hypot(prince.x-memory.marker.x,prince.y-memory.marker.y)<2*TILE){memory.duelStarted=true;memory.duelAt=now;const demon=mkUnit('champion',1,memory.marker.x+2*TILE,memory.marker.y,{guard:1,hx:memory.marker.x+2*TILE,hy:memory.marker.y});demon.hp=3000;memory.duelEnemy=demon.id;orderAttack(prince,demon);orderAttack(demon,prince);centerOn(memory.marker.x,memory.marker.y);cam.z0=14;msg('At the pass: Siamak faces the Black Demon.','warn');refreshMissionHUD();saveMemory(false)}else if(memory.duelStarted&&!memory.duelResolved&&now-memory.duelAt>=8){memory.duelResolved=true;if(prince){prince.dead=true;prince.fallen=false;sel=sel.filter(id=>id!==prince.id);fxs.push({t:'hit',x:prince.x,y:prince.y,life:.8,max:.8})}const demon=byId.get(memory.duelEnemy);if(demon)demon.dead=true;sfx('death',memory.marker.x,memory.marker.y);saveMemory(false);showSiamakAftermath();return}refreshMissionHUD();return}
  if(s.kind==='build')done=has(s.type);
  if(s.kind==='prepare')done=people.length>=8&&army.filter(e=>e.type!=='companion').length>=8&&has('tower');
  if(s.kind==='stock')memory.actionReady=afford(s.cost);
  if(['fight','capture','race'].includes(s.kind)){done=memory.targets.length>0&&memory.targets.every(id=>{const e=byId.get(id);return !alive(e)||e.team===0});if(s.kind==='capture'&&done)memory.writing=true;if(s.kind==='race'&&elapsed>s.seconds&&!done){defeat();return}}
  if(s.kind==='reach'&&ariel&&memory.marker)done=Math.hypot(ariel.x-memory.marker.x,ariel.y-memory.marker.y)<3*TILE;
  if(s.kind==='escort'){if(!memory.escorting&&ariel&&Math.hypot(ariel.x-memory.marker.x,ariel.y-memory.marker.y)<4*TILE){memory.escorting=true;memory.marker={x:14*TILE,y:67*TILE};for(const id of memory.targets){const e=byId.get(id);if(e)e.team=0}msg('The refugees join you. Bring them to your starting refuge.','good')}if(memory.escorting){if(memory.targets.some(id=>!alive(byId.get(id)))){defeat();return}done=memory.targets.every(id=>{const e=byId.get(id);return Math.hypot(e.x-14*TILE,e.y-67*TILE)<6*TILE})}}
  if(['hold','tax','famine','succession'].includes(s.kind)){const waves=s.waves||3;if(memory.wave<waves&&elapsed>(memory.id===1?60+memory.wave*80:20+memory.wave*(s.seconds-30)/waves)){launchMemoryWave(memory.wave++);}done=elapsed>=s.seconds&&(!s.n||people.length>=s.n);if(memory.id===1&&s.kind==='hold')done=memory.wave>=3&&people.length>0&&!ents.some(e=>e.memoryWave&&alive(e));if(['tax','famine'].includes(s.kind)){const tick=Math.floor(elapsed/15);if(tick>(memory.drainTick||0)){memory.drainTick=tick;const key=s.kind==='famine'?'food':'gold';res[key]=Math.max(0,res[key]-25);if(s.kind==='famine'&&res.food===0)for(const p of people){p.hp-=3;if(p.hp<=0)kill(p,null)}}}if(s.kind==='succession'){const reign=Math.min(5,Math.floor(elapsed/120)+1);if(reign!==memory.reign){memory.reign=reign;msg('A new ruler: '+['food tribute','gold tribute','military levy','wood tribute','Glory tribute'][reign-1]+'.','warn');const key=['food','gold','food','wood','farr'][reign-1];res[key]=Math.max(0,res[key]-100)}}}
  if(['blind','ambush'].includes(s.kind))done=army.length>=s.n;
  if(s.kind==='rescue'){if(now>=memory.rescueAt){spawnAlly('villager');memory.rescueAt=now+25;msg('The cooks have saved another youth.','good')}memory.detection=ents.some(e=>e.team===1&&alive(e)&&Math.hypot(e.x-14*TILE,e.y-64*TILE)<8*TILE)?memory.detection+.5:Math.max(0,memory.detection-.25);if(elapsed>60&&memory.wave<3&&elapsed>60+memory.wave*140){launchMemoryWave(memory.wave++);}if(memory.detection>=30){defeat();return}done=people.length>=s.n;}
  if(s.kind==='tribute')done=memory.deliveries>=s.n;
  if(s.kind==='duel'&&memory.targets.every(id=>!alive(byId.get(id)))){memory.duels++;if(memory.duels>=s.n)done=true;else spawnDuel()}
  if(s.kind==='court')done=memory.goal>=s.n;
  if(memory.id===25){const winter=Math.floor(now/120)%2===1;if(winter!==memory.winter){memory.winter=winter;RATE.bush*=winter?.6:1/.6;RATE.farm*=winter?.6:1/.6;msg(winter?'Winter: food gathering slows.':'Spring: food gathering recovers.')}}
  if(memory.id===60&&ariel)ariel.hp=Math.max(40,ariel.hp-.35);
  if(!people.length&&!ents.some(e=>e.team===0&&['tc','cave'].includes(e.type)&&alive(e))){defeat();return}
  if(done){msg('Objective complete: '+s.text,'good');res.farr+=memory.id>1?15:0;advanceStage()}else refreshMissionHUD();};

const originalKill=kill, originalUpdBld=updBld, originalUpdUnit=updUnit, originalCommand=commandInner;
kill=function(e,by){if(e.captureChief&&by?.team===0){e.team=0;e.hp=DEF[e.type].hp;e.captureChief=false;e.state='idle';e.target=0;spawnAlly('villager');res.farr+=10;msg('A demon chief is captured alive and joins the workers.','good');return}originalKill(e,by);if(e.type==='cave'&&e.team===0&&e.dead)defeat();};
updBld=function(b,dt){originalUpdBld(b,dt*(b.id===blessing?1.2:1))};
updUnit=function(e,dt){if(e.type==='priest'){const t=ents.find(b=>b.type==='temple'&&b.team===0&&b.done&&alive(b)&&Math.hypot(b.x-e.x,b.y-e.y)<5*TILE);if(t&&e.state!=='move')res.farr+=.6*dt*(memory?.prayerMultiplier||1)*(t.id===blessing?1.2:1)}if(memory?.healing&&e.team===0&&e.state!=='attack')e.hp=Math.min(DEF[e.type].hp,e.hp+dt*.5);originalUpdUnit(e,dt*(e.type==='villager'&&e.target===blessing&&e.anim==='work'?1.2:1));if(e.type==='caravan'&&e.team===0&&e.state==='idle'){const post=byId.get(memory.tradepost),market=ents.find(b=>b.type==='market'&&b.team===0&&b.done&&alive(b));if(post&&market){const dest=e.tradeReturn?market:post;if(Math.hypot(e.x-dest.x,e.y-dest.y)<5*TILE){if(e.tradeReturn){res.gold+=40;e.tradeReturn=false}else e.tradeReturn=true}const next=e.tradeReturn?market:post;orderMove(e,next.x,next.y)}}};
commandInner=function(x,y,t,S){if(blessingMode){if(t?.kind==='bld'&&t.team===0){blessing=t.id;memory.blessing=blessing;blessingMode=false;msg(DEF[t.type].name+' blessed: works 20% faster.','good');refreshMissionHUD()}else{blessingMode=false;msg('Movement order.');refreshMissionHUD();originalCommand(x,y,t,S)}return}originalCommand(x,y,t,S)};
const originalLeftClick=leftClick;
leftClick=function(x,y,shift){if(blessingMode){const e=pickEnt(x,y);if(e?.kind==='bld'&&e.team===0){commandInner(0,0,e,[]);return}blessingMode=false;msg('Blessing selection cancelled.');refreshMissionHUD();}originalLeftClick(x,y,shift)};
const originalCmdList=cmdList, originalCanDo=canDo, originalDoAct=doAct;
cmdList=function(){return originalCmdList().filter(c=>{const [a,t]=c.act.split(':');if(a==='build'||a==='train')return available(t);if(c.act==='ageup')return age<currentLevel().maxAge;return true})};
canDo=function(act){const [a,t]=act.split(':');if((a==='build'||a==='train')&&!available(t))return false;return originalCanDo(act)};
doAct=function(act){if(!canDo(act)){msg('This action is not available in the current memory or age.','warn');return}originalDoAct(act)};
const originalFog=updateFog;
updateFog=function(){if(!memory?.blind){originalFog();return}const saved={};for(const t in DEF)if(DEF[t].los){saved[t]=DEF[t].los;DEF[t].los=2}originalFog();for(const t in saved)DEF[t].los=saved[t]};

function refreshMissionHUD(){if(!memory||!campaignActive)return;const l=currentLevel(),s=PLANS[memory.id][memory.stage];$('#memory-title').textContent=String(l.id).padStart(2,'0')+' · '+l.title;$('#memory-age').textContent='Maximum '+AGES[l.maxAge];const elapsed=now-memory.stageAt;let extra='';if(s?.seconds)extra=' · '+Math.max(0,Math.ceil(s.seconds-elapsed))+'s remaining';if(s?.kind==='prepare')extra=' · '+ents.filter(e=>e.type==='villager'&&e.team===0&&alive(e)).length+'/8 villagers · '+ents.filter(e=>e.team===0&&alive(e)&&e.type!=='companion'&&['inf','arc','cav','siege'].includes(DEF[e.type].cls)).length+'/8 defenders · '+(ents.some(e=>e.type==='tower'&&e.team===0&&e.done&&alive(e))?'watchtower ready':'build a watchtower');if(memory.id===1&&s?.kind==='hold')extra=' · '+memory.wave+'/3 waves · '+ents.filter(e=>e.memoryWave&&alive(e)).length+' enemies remaining'+(memory.wave<3?' · next wave in '+Math.max(0,Math.ceil(60+memory.wave*80-elapsed))+'s':'');if(s?.kind==='rescue')extra=' · '+ents.filter(e=>e.type==='villager'&&e.team===0&&alive(e)).length+'/40 people · detection '+Math.floor(memory.detection||0)+'/30';if(s?.kind==='tribute')extra=' · '+memory.deliveries+'/'+s.n+' delivered';if(s?.kind==='duel')extra=' · '+memory.duels+'/'+s.n+' duels';$('#memory-objective').textContent=(s?.text||'Memory complete')+extra;const b=byId.get(blessing);$('#blessing-state').textContent=b&&alive(b)?DEF[b.type].name+' · +20%':'No building blessed';const act=$('#mission-action');act.hidden=!s||!['stock','tribute','puzzle','court'].includes(s.kind);act.disabled=false;if(s?.kind==='stock'){act.textContent='Commit '+costLong(s.cost);act.disabled=!afford(s.cost)}if(s?.kind==='tribute'){act.textContent='Send gift caravan · 120 gold, 40 wood';act.disabled=!afford(s.cost)||!ents.some(e=>e.type==='market'&&e.done&&e.team===0&&alive(e))}if(s?.kind==='puzzle')act.textContent='Meet the wise minister';if(s?.kind==='court'){act.textContent='Hold audience · 100 food, 80 gold ('+memory.goal+'/'+s.n+')';act.disabled=!afford({food:100,gold:80})}}
function missionAction(){if(paused||gameOver)return;const s=PLANS[memory.id][memory.stage];if(s.kind==='stock'&&afford(s.cost)){pay(s.cost);advanceStage()}else if(s.kind==='tribute'&&afford(s.cost)){const market=ents.find(e=>e.type==='market'&&e.done&&e.team===0&&alive(e));if(!market)return;pay(s.cost);const p=spawnSpot(market);const e=mkUnit('caravan',0,p.x,p.y);e.gift=true;orderMove(e,memory.marker.x,memory.marker.y);memory.gifts=memory.gifts||[];memory.gifts.push(e.id)}else if(s.kind==='puzzle'){showMemoryCard('The wise minister','Chess and backgammon','<p>On the chessboard, which piece must be protected for the kingdom to survive?</p>',[{t:'The king',f:()=>showMemoryCard('A game of time and chance','The minister’s reply','<p>Chess tests foresight. Backgammon adds the turn of the dice: a reminder that wisdom must also respond to chance.</p>',[{t:'Present backgammon to the court',f:()=>{closeModal();advanceStage()}}])},{t:'A pawn',f:()=>msg('The minister invites you to reconsider.')}])}else if(s.kind==='court'&&afford({food:100,gold:80})){pay({food:100,gold:80});memory.goal++;msg(memory.goal%2?'The court supports Ariel’s counsel.':'The Whisperer’s accusation is answered.','good')}refreshMissionHUD()}
const originalUpdate=update;
update=function(dt){originalUpdate(dt);if(!campaignActive||!memory||gameOver)return;for(const id of memory.gifts||[]){const e=byId.get(id);if(e&&alive(e)&&memory.marker&&Math.hypot(e.x-memory.marker.x,e.y-memory.marker.y)<5*TILE){e.gift=false;e.dead=true;memory.deliveries++;memory.gifts=memory.gifts.filter(x=>x!==id);msg('A gift caravan arrives.','good')}}if(now-(memory.lastSave||0)>45){memory.lastSave=now;saveMemory(false)}};

function readSave(){try{const s=JSON.parse(localStorage.getItem(RUN_KEY));return s&&s.version===CAMPAIGN_VERSION&&s.memory?.id>=1&&s.memory?.id<=62&&Array.isArray(s.ents)?s:null}catch(_){return null}}
function saveMemory(notify=true){if(!memory||gameOver)return false;const data={version:CAMPAIGN_VERSION,memory,ents:ents.filter(e=>!e.dead).map(e=>{const {tgt,...rest}=e;return rest}),res,age,now,nextId,blessing,powers,techs:[...techs],expl:Array.from(expl),reveals};try{localStorage.setItem(RUN_KEY,JSON.stringify(data));if(notify)msg('Memory saved at '+Math.floor(now/60)+':'+String(Math.floor(now%60)).padStart(2,'0')+' · '+Math.floor(res.food)+' food, '+Math.floor(res.wood)+' wood.','good');return true}catch(_){if(notify)msg('Could not save: browser storage is full or unavailable.','warn');return false}}
function resumeMemory(){const s=readSave();if(!s)return;if(s.memory.id===1&&s.memory.settlementRevision!==3){$('#campaign').hidden=true;showMemoryCard('A new mountain settlement','Opening mission rebuilt','<p>This saved attempt uses the old cave scenario. Begin the rebuilt mission with a settlement, five villagers, six defenders and supplies. Your campaign unlocks are kept.</p>',[{t:'Begin rebuilt mission',f:()=>startMemory(1)},{t:'Campaign',f:openCampaign}]);return;}$('#campaign').hidden=true;campaign.current=s.memory.id;memory=clone(s.memory);campaignActive=true;setupWorld();memory=clone(s.memory);clearWorld3D();ents=[];byId.clear();occ.fill(0);blocked.set(tblk);for(const t of s.techs){if(TECH[t]){TECH[t].apply();techs.add(t)}}for(const p of memory.patrons)applyPatron(p);if(memory.winter){RATE.bush*=.6;RATE.farm*=.6}ents=s.ents;byId=new Map(ents.map(e=>[e.id,e]));for(const e of ents)if(e.kind!=='unit'){stampE(e,true);if(e.type!=='tree')onPlaced(e)}nextId=s.nextId;res=s.res;age=s.age;now=s.now;blessing=s.blessing;powers=s.powers;reveals=s.reveals;expl.set(s.expl);const activeTrees=new Set(ents.filter(e=>e.type==='tree').map(e=>e.ti));TREES.forEach((t,k)=>{if(!activeTrees.has(k))hideTree(k)});OBJ=PLANS[memory.id].filter(x=>x.kind!=='event').map((x,i)=>({id:'memory-'+i,text:x.text,done:PLANS[memory.id].indexOf(x)<memory.stage,hidden:PLANS[memory.id].indexOf(x)>memory.stage}));paused=false;gameOver=false;closeModal();recalcPop();updateFog();refreshPowers();refreshObj();refreshMissionHUD();if(memory.pendingPatron)choosePatron();else if(!memory.started)memoryIntro();else if(PLANS[memory.id][memory.stage]?.kind==='side'){const st=memory.stage;memory.started=false;beginStage()}else if(PLANS[memory.id][memory.stage]?.kind==='event'){const ev=PLANS[memory.id][memory.stage];showMemoryCard(ev.text,'Ariel remembers','<p>'+esc(ev.body)+'</p>',[{t:'Continue',f:()=>{closeModal();advanceStage()}}])}}

openMenu=function(){if(!$('#modal').hidden)return;showMemoryCard('Ariel of the Shahnameh','Paused','<p>'+esc(currentLevel().title)+' · Memory '+currentLevel().id+' / 62</p><p>Progress saves automatically. Use Save memory before leaving. Select Ariel, then Bless building to move his 20% work bonus.</p>',[{t:'Resume',f:closeModal},{t:'Save memory',f:()=>saveMemory()},{t:'Campaign',f:()=>{saveMemory(false);openCampaign()}},{t:'Restart memory',f:restart}])};
const originalHUD=hudTick;
hudTick=function(){originalHUD();refreshMissionHUD();$('#age').textContent=AGES[age]+(age<currentLevel().maxAge?' ↑':' · limit');const h=$('#memory-hud');h.style.top=($('#top').getBoundingClientRect().bottom+12)+'px';$('#obj').style.top=(h.getBoundingClientRect().bottom+10)+'px';};
const originalOverlay=drawOverlay;
drawOverlay=function(){originalOverlay();if(!campaignActive||!memory?.marker||$('#campaign').hidden===false)return;const p=toScreen(memory.marker.x/TILE,heightAt(memory.marker.x/TILE,memory.marker.y/TILE)+.5,memory.marker.y/TILE);if(p.z>1)return;octx.save();octx.setTransform(DPR,0,0,DPR,0,0);octx.fillStyle='#f6d58a';octx.strokeStyle='#1b2a31';octx.lineWidth=4;octx.font='bold 16px sans-serif';octx.textAlign='center';const text=memory.escorting?'Return to refuge':'◆ Mission destination';octx.strokeText(text,p.x,p.y-20);octx.fillText(text,p.x,p.y-20);octx.restore()};

function installCampaignUI(){document.title='Ariel of the Shahnameh';const style=document.createElement('style');style.textContent=`
#campaign{position:fixed;inset:0;z-index:1000;background:radial-gradient(ellipse at 80% 0,#394b4a,#122328 50%,#091318);color:#eee4cd;overflow:auto;padding:clamp(18px,4vw,52px);box-sizing:border-box}#campaign[hidden]{display:none}#campaign header{max-width:1200px;margin:auto;border-bottom:1px solid #90794b;padding-bottom:18px}#campaign h1{font:clamp(32px,5vw,58px) Georgia,serif;margin:8px 0;color:#efcf8b}#campaign .ey{letter-spacing:.2em;font-size:12px;text-transform:uppercase;color:#b8c8c2}#campaign .campaign-layout{display:grid;grid-template-columns:minmax(260px,1fr) minmax(300px,1.1fr);gap:32px;max-width:1200px;margin:24px auto}#campaign-list{max-height:58vh;overflow:auto;padding-right:12px}#campaign h3{font:20px Georgia,serif;color:#d5b982;margin:24px 0 12px}.memory-entry{display:flex;align-items:center;text-align:left;width:100%;gap:12px;padding:13px 10px;border:0;border-bottom:1px solid #34494b;background:transparent;color:#dbdfd3;font-size:14px;cursor:pointer}.memory-entry span{color:#d6b476;font-size:17px}.memory-entry b{flex:1}.memory-entry small{font-size:11px;color:#adbab5}.memory-entry.selected{background:#344747;box-shadow:inset 3px 0 #e2bc73}#campaign-detail{padding:28px;background:#172c31;border:1px solid #5d6656;align-self:start}#campaign-detail h2{font:34px Georgia,serif;color:#f1d59a;margin:14px 0}#campaign-detail p{line-height:1.65}#campaign button:disabled{opacity:.4;cursor:not-allowed}.campaign-tools{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.campaign-tools button{padding:10px 16px}.campaign-tools small{margin-left:auto;color:#bbcebf}#memory-hud{position:absolute;left:12px;top:185px;max-width:360px;padding:10px 12px;background:#132a2de8;border-left:2px solid #b99c62;z-index:12;color:#e6dbc0;font:13px/1.4 sans-serif;pointer-events:auto}#memory-hud b{display:block;color:#f3d493}#memory-hud small{color:#aebfb5}#memory-hud button{margin:5px 4px 0 0;background:#364a46;border:1px solid #8d805d;color:#f5e3bd;padding:7px;cursor:pointer}#memory-hud button:disabled{opacity:.5}#memory-objective{margin:7px 0}#obj{top:350px;max-width:330px}#objlist{max-height:22vh;overflow:auto}.memory-modal .card{display:block!important;max-width:790px!important;max-height:85vh;overflow:auto}.memory-modal #story-visual{display:none!important}.memory-modal #m-text{line-height:1.6}.memory-modal #m-acts{display:flex;flex-wrap:wrap;gap:8px}.memory-modal blockquote{font:28px Georgia,serif;color:#e9ce94;margin:22px 0}.narrator{color:#aac2be;font-size:13px}.memory-modal .big{font-size:16px;padding:12px 18px}.memory-modal #m-title{font-size:36px}@media(max-width:760px){#campaign .campaign-layout{grid-template-columns:1fr;gap:16px}#campaign-list{max-height:30vh}#campaign-detail{padding:18px}#memory-hud{top:170px;max-width:270px;font-size:11px}#obj{top:340px;max-width:280px}#campaign h1{font-size:32px}}`;
document.head.append(style);const shell=document.createElement('section');shell.id='campaign';shell.hidden=true;shell.innerHTML='<header><p class="ey">Nine acts · Sixty-two memories · One guardian</p><h1>Ariel of the Shahnameh</h1><p>“I was there. Let me tell you.”</p><div class="campaign-tools"><button class="big" id="resume-memory">Continue saved memory</button><button class="big ghost" id="return-memory">Return to game</button><small id="campaign-progress"></small></div></header><div class="campaign-layout"><nav id="campaign-list" aria-label="The 62 memories"></nav><article id="campaign-detail"></article></div>';document.body.append(shell);$('#resume-memory').onclick=resumeMemory;$('#return-memory').onclick=()=>{shell.hidden=true;paused=false};const hud=document.createElement('aside');hud.id='memory-hud';hud.innerHTML='<b id="memory-title"></b><small id="memory-age"></small><p id="memory-objective"></p><button id="bless-building">Bless building</button><small id="blessing-state"></small><button id="mission-action" hidden></button>';$('#game').append(hud);$('#bless-building').onclick=()=>{if(paused||gameOver)return;const a=ents.find(e=>e.type==='ariel'&&alive(e));if(!a){msg('Wait for Ariel to return.');return}blessingMode=!blessingMode;if(blessingMode){setSel([a.id]);msg('Click one of your buildings. The blessing moves there.')}else msg('Blessing selection cancelled.')};$('#mission-action').onclick=missionAction;$('#r-farr').title='Glory — priests at temples and heroic deeds';$('#b-hero small').textContent='Ariel & companions · H';}
// Distinct silhouettes for the new economy, rather than a row of renamed houses.
function cm(g,geometry,color,x=0,y=0,z=0){const m=new T3.Mesh(geometry,patch(new T3.MeshStandardMaterial({color,roughness:.86})));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;g.add(m);return m}
const cb=(g,w,h,d,col,x=0,y=h/2,z=0)=>cm(g,new T3.BoxGeometry(w,h,d),col,x,y,z);
// A solid mountain ridge blocks movement; its southern rock face meets the cave mouth.
define('mountain','store',{name:'Mountain Ridge',w:16,h:8,hp:1000000,cost:undefined,drop:0,popc:0,los:0,desc:'Impassable mountain behind the settlement.'});
for(const [type,name] of [['ridge','Rocky Ridge'],['mesa','Sandstone Mesa'],['copse','Mountain Grove'],['stonefield','Stone Field'],['snowcrest','Snowy Crag']])define(type,'store',{name,w:3,h:3,hp:1000000,invul:1,cost:undefined,drop:0,popc:0,los:0,desc:'Natural terrain.'});
BUILD.mountain=g=>{const nx=32,nz=18,pos=[],colors=[],indices=[];for(let z=0;z<=nz;z++)for(let x=0;x<=nx;x++){const px=x/nx*16-8,pz=z/nz*8-4;const edge=Math.pow(Math.sin(Math.PI*x/nx)*Math.sin(Math.PI*z/nz),.55);const peaks=5.3+1.4*Math.sin(px*.85)+.8*Math.cos(pz*1.5);const h=Math.max(0,edge*peaks+.15*Math.sin(x*12+z*7)*edge);pos.push(px,h,pz);const c=new T3.Color(h>5.6?0xb6ad9b:0x837b68);c.multiplyScalar(.84+.17*Math.sin(h*9)+.08*Math.cos(px*3));colors.push(c.r,c.g,c.b)}for(let z=0;z<nz;z++)for(let x=0;x<nx;x++){const i=z*(nx+1)+x;indices.push(i,i+nx+1,i+1,i+1,i+nx+1,i+nx+2)}const geo=new T3.BufferGeometry();geo.setAttribute('position',new T3.Float32BufferAttribute(pos,3));geo.setAttribute('color',new T3.Float32BufferAttribute(colors,3));geo.setIndex(indices);geo.computeVertexNormals();const m=new T3.Mesh(geo,patch(new T3.MeshStandardMaterial({vertexColors:true,roughness:1,flatShading:true})));m.castShadow=m.receiveShadow=true;g.add(m);};
BUILD.cave=g=>{for(const [x,y,z,sx,sy,sz] of [[-1.35,1.15,-.3,1.1,1.7,1.7],[1.3,1.2,-.5,1.1,1.8,1.8],[0,2.45,-.6,1.8,.85,1.8],[-1.9,.5,-1.1,1,.8,1.4],[1.8,.5,-1.1,1,.9,1.4]]){const r=cm(g,new T3.DodecahedronGeometry(1,0),0x857d68,x,y,z);r.scale.set(sx,sy,sz)}const dark=new T3.Mesh(new T3.PlaneGeometry(2,2.4),new T3.MeshBasicMaterial({color:0x100e0c}));dark.position.set(0,1.15,-.35);g.add(dark);cb(g,2,.07,2.3,0x665b46,0,.02,.35);for(const x of [-1.15,1.15]){cb(g,.1,1.2,.1,0x4e3624,x,.6,1);cm(g,new T3.ConeGeometry(.12,.3,7),0xffad39,x,1.25,1)} };

BUILD.wall=g=>{cb(g,.85,1.4,.65,0xa18d68);for(const x of [-.3,0,.3])cb(g,.2,.25,.7,0xb4a37e,x,1.48)};
BUILD.blacksmith=g=>{
  // Open-sided stone forge: the fire, anvil and tool bench remain visible from above.
  cb(g,2.95,.16,2.9,0x9a896d,0,.08,0);
  for(let i=0;i<19;i++){const x=((i*7)%17)/17*2.6-1.3,z=((i*11)%19)/19*2.5-1.25;cb(g,.3+(i%3)*.06,.025,.21, i%3===0?0xb19b78:0x85745d,x,.18,z)}
  cb(g,2.85,1.18,.26,0x9c8c71,0,.74,-1.27);
  cb(g,.22,.76,2.2,0x8e7c61,-1.36,.5,-.18);
  for(const x of [-1.22,1.22])for(const z of [-1.05,.15])cb(g,.19,2.02,.2,0x5d4330,x,1.11,z);
  for(const x of [-.69,.69]){const roof=cb(g,1.5,.16,1.53,0x694a32,x,2.22,-.62);roof.rotation.z=x<0?.25:-.25;cb(g,.1,.17,1.54,0x9b7650,x,2.1,-.62)}
  cb(g,.28,.3,1.56,0x4b3529,0,2.4,-.62);
  // Stone firebox, dark opening, and bright coals under a tall vent.
  cb(g,1.02,1.22,.94,0x796b59,-.79,.79,-.65);
  cb(g,.66,.68,.045,0x211d19,-.79,.7,-.14);
  const fire=new T3.Mesh(new T3.PlaneGeometry(.51,.38),new T3.MeshBasicMaterial({color:0xff842d,side:T3.DoubleSide}));fire.position.set(-.79,.66,-.103);g.add(fire);
  cb(g,.72,.13,.18,0xb09a75,-.79,1.16,-.1);
  cb(g,.53,1.55,.55,0x8b7a65,-.79,2.18,-.76);
  cb(g,.72,.16,.72,0xb09d7a,-.79,3,-.76);
  for(let i=0;i<4;i++){const coal=cm(g,new T3.DodecahedronGeometry(.09+(i%2)*.035,0),i%2?0xffa23e:0x3a2c24,-.98+i*.13,.42,-.07);coal.scale.y=.6}
  // The heavy anvil is the visual focus of the working yard.
  cm(g,new T3.CylinderGeometry(.3,.38,.58,9),0x6c4e32,.3,.48,.5);
  cb(g,.78,.18,.42,0x353c3e,.31,.85,.5);
  cb(g,.51,.12,.31,0x5b6260,.27,.99,.5);
  const horn=cm(g,new T3.ConeGeometry(.16,.47,9),0x42494b,.87,.87,.5);horn.rotation.z=-Math.PI/2;
  // Tools on the back rack, quenching trough and stacked iron stock.
  cb(g,1.06,.11,.13,0x604832,.73,1.27,-1.08);
  for(let i=0;i<4;i++){const x=.39+i*.23;cb(g,.055,.59-(i%2)*.12,.055,0x42494a,x,.91,-.97);cb(g,.17,.08,.08,0x353b3d,x,.62+(i%2)*.06,-.94)}
  cb(g,.62,.3,.48,0x67503b,1.02,.34,.68);cb(g,.48,.025,.34,0x295058,1.02,.5,.68);
  for(let i=0;i<3;i++)cb(g,.65,.06,.07,0x414749,-.87+i*.11,.25,.74+i*.13);
};
BUILD.range=g=>{cb(g,2.7,.12,2.5,0x8e7b58);cb(g,2.6,.7,.16,0x866d48,0,.45,-1);for(const x of [-.8,0,.8]){cb(g,.07,1.2,.08,0x654b2e,x,.6,-.5);const disk=cm(g,new T3.CylinderGeometry(.31,.31,.08,24),0xd0b985,x,.9,-.48);disk.rotation.x=Math.PI/2;const bull=cm(g,new T3.CylinderGeometry(.13,.13,.085,20),0x884339,x,.9,-.42);bull.rotation.x=Math.PI/2}};
BUILD.market=g=>{cb(g,2.7,.1,2.5,0xb39b72);for(const x of [-.85,.85]){for(const z of [-.7,.7])cb(g,.08,1.2,.08,0x6d4c2e,x,.65,z);const roof=cm(g,new T3.ConeGeometry(.9,.45,4),x<0?0x36666a:0x96583a,x,1.4,0);roof.rotation.y=Math.PI/4;cb(g,.85,.45,.5,0x876d47,x,.3,.35);for(let i=0;i<3;i++)cm(g,new T3.SphereGeometry(.13,8,6),0xb89b51,x-.25+i*.25,.6,.35)}};
BUILD.nest=g=>{cb(g,1.5,.45,1.5,0x817c6d);for(let i=0;i<16;i++){const a=i/16*Math.PI*2;const b=cb(g,.09,.1,1.1,0x786342,Math.cos(a)*.7,.65,Math.sin(a)*.7);b.rotation.y=-a}for(const x of [-.25,.22]){const egg=cm(g,new T3.SphereGeometry(.2,16,12),0xe3d8b1,x,.72,0);egg.scale.y=1.3}};
BUILD.observatory=g=>{cm(g,new T3.CylinderGeometry(.9,1.15,1,24),0xb19b71,0,.5,0);cm(g,new T3.CylinderGeometry(1.1,1.1,.15,24),0xd1bf95,0,1.08,0);const ring=cm(g,new T3.TorusGeometry(.55,.04,8,32),0xc09e54,0,1.8,0);ring.rotation.x=.7;const ring2=cm(g,new T3.TorusGeometry(.55,.04,8,32),0xc09e54,0,1.8,0);ring2.rotation.y=.8;cm(g,new T3.SphereGeometry(.14,16,12),0x8bb3b1,0,1.8,0);cb(g,.1,.7,.1,0x9a814d,0,1.4,0)};
const campaignHumanSpec=humanSpec;
humanSpec=function(type,team){type=uAliases[type]||type;if((type==='spearman'||type==='companion')&&currentLevel().id===1)return{tunic:0x92704a,trim:0xbba074,pants:0x604d34,skin:0xb58664,hair:0x29211c,beard:0x36281c,tools:['w_club'],wk:'club'};return campaignHumanSpec(type,team)};
const campaignUnitModel=unitModel,campaignAnim=animUnit;
unitModel=function(type,team){if(type!=='ram')return campaignUnitModel(type,team);const root=new T3.Group();cb(root,1,.18,1.5,0x6f5233,0,.4,0);cb(root,.24,.24,2,0x493f32,0,.7,.1);const wheels=[];for(const x of [-.55,.55])for(const z of [-.5,.5]){const w=cm(root,new T3.CylinderGeometry(.25,.25,.12,16),0x463d32,x,.26,z);w.rotation.z=Math.PI/2;wheels.push(w)}return{root,kind:'ram',wheels}};
animUnit=function(R,e,t,dt){if(R.kind==='ram'){if(e.moving)for(const w of R.wheels)w.rotation.x+=dt*3;return}campaignAnim(R,e,t,dt)};
DEF.serpent.name='Enemy Warrior';DEF.bowman.name='Enemy Archer';BASE_DEF.serpent=clone(DEF.serpent);BASE_DEF.bowman=clone(DEF.bowman);
define('bounddemon','div',{name:'Bound Demon',age:4,pop:4,cost:{gold:160,farr:50},time:24,desc:'A powerful mythic fighter. Enemy heroes counter it.'});
uAliases.bounddemon='div';DEF.temple.trains.push('bounddemon');BASE_DEF.temple=clone(DEF.temple);
define('stonedefender','spearman',{name:'Stone Defender'});uAliases.stonedefender='spearman';
const campaignPortrait=portrait;
portrait=function(type,team,lvl){return campaignPortrait(type==='spearman'&&currentLevel().id===1?'stonedefender':type,team,lvl)};
define('herd','bush',{name:'Sheep Herd',amt:600,desc:'Villagers gather food from the herd.'});
define('hunt','bush',{name:'Wild Game',amt:450,desc:'Hunt wild animals for food.'});
define('fish','bush',{name:'Fishing Bank',amt:1200,desc:'Gather food from the river bank.'});
Object.assign(RATE,{herd:.9,hunt:.9,fish:.8});Object.assign(BASE_RATE,{herd:.9,hunt:.9,fish:.8});
const campaignMakeObj=makeObj;
makeObj=function(e){if(!['herd','hunt','fish'].includes(e.type))return campaignMakeObj(e);const root=new T3.Group();if(e.type==='fish'){cb(root,1,.08,.6,0x755a37);for(const z of [-.2,.2]){const f=cm(root,new T3.SphereGeometry(.16,10,6),0xa2b9b5,0,.15,z);f.scale.set(1.8,.4,.6)}}else{for(const x of [-.2,.2])for(const z of [-.25,.25])cb(root,.08,.35,.08,0x4d4031,x,.18,z);const b=cm(root,new T3.SphereGeometry(.35,14,10),e.type==='herd'?0xd5cbb3:0x92734e,0,.48,0);b.scale.set(.8,.8,1.25);cm(root,new T3.SphereGeometry(.18,12,8),0x6c5b45,0,.6,.37)}root.position.set(e.x/TILE,heightAt(e.x/TILE,e.y/TILE),e.y/TILE);const o={kind:'res',root};scene.add(root);objs.set(e.id,o);return o};
const campaignSetup=setupWorld;
const COMPANIONS={1:'Siamak',2:'Hushang',3:'Tahmuras',4:'Jamshid',7:'Iraj',8:'Manuchehr',9:'Sam',10:'Zal',11:'Zal',12:'Nowzar',13:'Rostam',14:'Kay Qobad',15:'Kavus',16:'Rostam',17:'Rostam',18:'Kavus',19:'Rostam',20:'Rostam',21:'Siavash',22:'Siavash',23:'Siavash',24:'Rostam',25:'Giv',26:'Kay Khosrow',27:'Kay Khosrow',28:'Forud',29:'Rostam',30:'Rostam',31:'Rostam',32:'Rostam',33:'Gudarz',34:'Kay Khosrow',35:'Kay Khosrow',36:'Goshtasp',37:'Goshtasp',38:'Esfandiyar',39:'Esfandiyar',40:'Faramarz',41:'The miller',42:'Darab',43:'Dara',44:'Alexander',45:'Ardashir',46:'Ardashir',47:'Shapur',48:'The people’s champion',49:'Bahram',50:'Bahram',51:'Bahram',52:'Sukhra',53:'The people’s champion',54:'Bozorgmehr',55:'Khosrow',56:'Bahram Chubin',57:'Bahram Chubin',58:'Khosrow Parviz',59:'Khosrow Parviz',60:'Khosrow Parviz',61:'The last defenders',62:'Yazdegerd III'};
setupWorld=function(){campaignSetup();if(COMPANIONS[memory.id]){DEF.companion.name=COMPANIONS[memory.id];if(!ents.some(e=>e.type==='companion'))mkUnit('companion',0,18*TILE,67*TILE)}for(const p of [[8,68],[24,72]]){const e=placeFree('hunt',2,...p);if(e)e.amt=600}if(memory.id>=3)placeFree('herd',2,8,59);if(memory.id>=4)placeFree('fish',2,40,51)};
const campaignTool=toolFor;
toolFor=function(e){return ['herd','hunt'].includes(e.workKind)?'w_axe':e.workKind==='fish'?'w_basket':campaignTool(e)};
const campaignCmds=cmdList,campaignCanDo=canDo,campaignDoAct=doAct;
const EXCHANGES={buyfood:{cost:{gold:100},gain:{food:80},name:'Buy food'},buywood:{cost:{gold:100},gain:{wood:80},name:'Buy wood'},sellfood:{cost:{food:100},gain:{gold:70},name:'Sell food'},sellwood:{cost:{wood:100},gain:{gold:70},name:'Sell wood'}};
cmdList=function(){const list=campaignCmds();if(!placing&&!targeting&&!rallying&&selEnts().some(e=>e.type==='wall'&&e.team===0&&e.done))list.push({act:'gate',ico:'wall',nm:'Build Gate',cost:DEF.gate.cost,tip:{name:'Build a gate',desc:'Convert this wall section into a guarded passage. Your units can cross when it is complete; enemies cannot.'}});if(!placing&&!targeting&&!rallying&&selEnts().some(e=>e.type==='market'&&e.team===0&&e.done)){for(const [k,v] of Object.entries(EXCHANGES))list.push({act:'exchange:'+k,ico:'market',nm:v.name,cost:v.cost,tip:{name:v.name,desc:'Receive '+costLong(v.gain)+'.'}})}return list};
canDo=function(act){if(act==='gate')return afford(DEF.gate.cost)&&selEnts().some(e=>e.type==='wall'&&e.team===0&&e.done);if(act.startsWith('exchange:'))return afford(EXCHANGES[act.slice(9)].cost)&&selEnts().some(e=>e.type==='market'&&e.team===0&&e.done);return campaignCanDo(act)};
doAct=function(act){if(act==='gate'){const b=selEnts().find(e=>e.type==='wall'&&e.team===0&&e.done);if(!b||!afford(DEF.gate.cost)){msg('Select a completed wall section and gather '+costLong(DEF.gate.cost)+'.','warn');return}pay(DEF.gate.cost);const old=objs.get(b.id);if(old){disposeVisual(old.root);objs.delete(b.id)}b.type='gate';b.done=false;b.bp=0;b.hp=1;const builders=ents.filter(e=>e.type==='villager'&&e.team===0&&alive(e)&&Math.hypot(e.x-b.x,e.y-b.y)<9*TILE).sort((a,c)=>Math.hypot(a.x-b.x,a.y-b.y)-Math.hypot(c.x-b.x,c.y-b.y)).slice(0,2);for(const v of builders)orderBuild(v,b);msg(builders.length?'Gate placed. Nearby villagers are building it.':'Gate placed. Select a villager and click it to finish construction.','good');refreshSel();return}if(act.startsWith('exchange:')){if(!canDo(act))return;const v=EXCHANGES[act.slice(9)];pay(v.cost);for(const [k,n] of Object.entries(v.gain))res[k]+=n;refreshSel();return}campaignDoAct(act)};
selectArmy=function(){const army=ents.filter(e=>e.kind==='unit'&&e.team===0&&alive(e)&&!['vil','trade','priest'].includes(DEF[e.type].cls));setSel(army.map(e=>e.id));msg(army.length+' fighters selected.')};
document.addEventListener('keydown',e=>{if(e.key==='Escape')blessingMode=false});
installCampaignUI();
const framePicture=document.createElement('figure');framePicture.className='ariel-frame';framePicture.innerHTML='<img alt="Ariel, the traveler in teal, tells his memories to Ferdowsi, the poet writing in cream robes." src="'+ARIEL_FRAME+'"><figcaption>Ariel remembers. Ferdowsi writes.</figcaption>';
$('#campaign header').prepend(framePicture);
const frameStyle=document.createElement('style');frameStyle.textContent='.ariel-frame{float:right;width:35%;max-width:330px;margin:0 0 10px 24px}.ariel-frame img{width:100%;display:block;border:1px solid #967748}.ariel-frame figcaption{color:#c5b894;font:12px Georgia,serif;margin-top:5px}#campaign header{display:flow-root}@media(max-width:640px){.ariel-frame{float:none;width:100%;max-width:none;margin:0 0 18px}.ariel-frame img{max-height:210px;object-fit:cover;object-position:50% 40%}}';document.head.append(frameStyle);

// Early settlement uses timber and hide structures, before monumental architecture.
const settledHouse=BUILD.house,settledTower=BUILD.tower,settledWall=BUILD.wall;
BUILD.house=(g,...a)=>{if(currentLevel().id!==1)return settledHouse(g,...a);g.userData.variant='mountain';cb(g,1.65,.7,1.65,0x9b8159,0,.35,0);const roof=cm(g,new T3.ConeGeometry(1.4,.9,4),0x6e6442,0,1.12,0);roof.rotation.y=Math.PI/4;cb(g,.5,.65,.04,0x30271c,0,.33,.84);};
let settlementTowerAlbedo=null;
BUILD.tower=(g,...a)=>{if(currentLevel().id!==1)return settledTower(g,...a);g.userData.variant='mountain';
  // Compact cylindrical mountain watchtower inspired by Iranian adobe and rubble-stone examples.
  const towerAlbedo=settlementTowerAlbedo||(settlementTowerAlbedo=new T3.TextureLoader().load(TOWER_TEXTURE,()=>requestWorldFrame()));towerAlbedo.encoding=T3.sRGBEncoding;towerAlbedo.wrapS=towerAlbedo.wrapT=T3.RepeatWrapping;towerAlbedo.anisotropy=8;const masonry=patch(new T3.MeshStandardMaterial({color:0xd3bfa3,map:towerAlbedo,bumpMap:towerAlbedo,bumpScale:.055,roughness:1}));
  const rubble=patch(new T3.MeshStandardMaterial({color:0x68604e,map:TX.rock,roughness:1}));
  const base=cm(g,new T3.CylinderGeometry(1.02,1.22,.6,20),0x726957,0,.29,0);base.material=rubble;
  const shaftGeo=new T3.CylinderGeometry(.77,1.03,2.9,20,8);
  const pp=shaftGeo.attributes.position;for(let i=0;i<pp.count;i++){const y=pp.getY(i),x=pp.getX(i),z=pp.getZ(i);const angle=Math.atan2(z,x);const weather=.025*Math.sin(angle*11+y*13)+.018*Math.cos(angle*23-y*7);pp.setXYZ(i,x*(1+weather),y,z*(1+weather))}shaftGeo.computeVertexNormals();
  const shaft=new T3.Mesh(shaftGeo,masonry);shaft.position.y=2.03;shaft.castShadow=shaft.receiveShadow=true;g.add(shaft);
  // Uneven rubble courses tie the tower to its rough base.
  for(let course=0;course<3;course++)for(let i=0;i<15;i++){const a=i/15*Math.PI*2+(course%2)*.12,r=1.11-course*.055;const rock=cm(g,new T3.DodecahedronGeometry(.14+(i%3)*.02,0),[0x6b6558,0x8b806b,0x746b59][(i+course)%3],Math.sin(a)*r,.17+course*.19,Math.cos(a)*r);rock.scale.set(1.35,.5,.75);rock.rotation.y=a}
  // Dark arrow slits sit flush in the wall, with weathered stone lintels.
  for(const a of [0,Math.PI*.5,Math.PI,Math.PI*1.5]){const r=.88,slit=cm(g,new T3.BoxGeometry(.13,.43,.012),0x171813,Math.sin(a)*r,2.22,Math.cos(a)*r);slit.rotation.y=a;const lintel=cm(g,new T3.BoxGeometry(.23,.055,.07),0x665c48,Math.sin(a)*(r+.035),2.49,Math.cos(a)*(r+.035));lintel.rotation.y=a}
  const dark=cm(g,new T3.BoxGeometry(.54,.83,.05),0x221c15,0,.73,1.025);cm(g,new T3.SphereGeometry(.27,12,7),0x221c15,0,1.13,1.025).scale.y=.45;
  for(const x of [-.33,.33])cb(g,.085,1.05,.075,0x5e4933,x,.73,1.065);
  cm(g,new T3.CylinderGeometry(.91,.91,.12,20),0x665d4b,0,3.48,0);
  // A low parapet and a few worn merlons leave real gaps for observation.
  const parapet=new T3.Mesh(new T3.CylinderGeometry(.98,.98,.31,20,1,true),masonry);parapet.position.y=3.68;parapet.castShadow=parapet.receiveShadow=true;g.add(parapet);
  for(let i=0;i<12;i++){if(i%4===3)continue;const a=(i+.5)/12*Math.PI*2;const h=.19+.06*Math.sin(i*3.7);const stone=new T3.Mesh(new T3.BoxGeometry(.28,h,.17),masonry);stone.position.set(Math.sin(a)*.91,3.88+h*.5,Math.cos(a)*.91);stone.rotation.y=a;stone.castShadow=stone.receiveShadow=true;g.add(stone)}
  for(let i=0;i<4;i++){const a=i*1.57+.35;const stain=cm(g,new T3.DodecahedronGeometry(.2,0),0x655d4d,Math.sin(a)*.92,1.2+(i%2)*.7,Math.cos(a)*.92);stain.scale.set(.5,.8,.18);stain.rotation.y=a}
};
BUILD.wall=(g,...a)=>{if(currentLevel().id!==1)return settledWall(g,...a);for(const x of [-.39,-.13,.13,.39]){cb(g,.18,1.3,.22,0x765638,x,.65,0);cm(g,new T3.ConeGeometry(.13,.25,4),0x97734a,x,1.42,0)}cb(g,1,.12,.15,0x4f3b2a,0,.4,.13);};
BUILD.gate=g=>{const wood=currentLevel().id===1,stone=wood?0x765638:0xb9a77e,trim=wood?0x9e7645:0xd6c6a0;cb(g,1,.10,.94,0x70674f,0,.05,0);for(const x of [-.39,.39]){cb(g,.2,1.7,.82,stone,x,.88,0);cb(g,.24,.16,.88,trim,x,1.77,0);cb(g,.25,.25,.25,trim,x,1.94,0)}cb(g,1,.22,.82,stone,0,1.76,0);cb(g,.72,.13,.54,0x185e68,0,1.58,0);cb(g,.50,.035,.9,0xc99c4f,0,.12,0);for(const x of [-.18,.18]){cb(g,.055,.8,.06,0x256f75,x,.48,x<0?-.33:.33);cb(g,.075,.08,.08,0xd7b56e,x,.86,x<0?-.33:.33)}};

const caveRockCanvas=document.createElement('canvas');caveRockCanvas.width=caveRockCanvas.height=128;const caveRockCtx=caveRockCanvas.getContext('2d'),caveRockPixels=caveRockCtx.createImageData(128,128);for(let y=0;y<128;y++)for(let x=0;x<128;x++){const n=142+18*Math.sin(x*.17+Math.sin(y*.09)*3)+12*Math.sin(y*.7+x*.06)+10*Math.sin(x*15.7+y*47.3),i=(y*128+x)*4;caveRockPixels.data.set([n,n*.94,n*.8,255],i)}caveRockCtx.putImageData(caveRockPixels,0,0);const caveRockTexture=new T3.CanvasTexture(caveRockCanvas);caveRockTexture.wrapS=caveRockTexture.wrapT=T3.RepeatWrapping;caveRockTexture.repeat.set(.8,.8);
const settlementBake=bakeGroup;
bakeGroup=function(g,key){return settlementBake(g,(currentLevel().id===1?'mountain-settlement-':'royal-')+key)};
BUILD.cave=g=>{const face=new T3.Shape();face.moveTo(-2.3,-.15);face.lineTo(2.3,-.15);face.quadraticCurveTo(2.7,1.5,1.9,2.4);face.quadraticCurveTo(1.7,3.5,.5,3.1);face.quadraticCurveTo(-1.5,3.7,-2.1,2);face.lineTo(-2.5,.9);face.closePath();const mouth=new T3.Path();mouth.moveTo(-.85,.02);mouth.lineTo(-.95,1.2);mouth.quadraticCurveTo(-.8,2.2,0,2.25);mouth.quadraticCurveTo(.9,2.1,.92,1.15);mouth.lineTo(.85,.02);mouth.closePath();face.holes.push(mouth);const geo=new T3.ExtrudeGeometry(face,{depth:2.4,bevelEnabled:true,bevelThickness:.15,bevelSize:.12,bevelSegments:2,curveSegments:16});const rock=new T3.Mesh(geo,patch(new T3.MeshStandardMaterial({color:0xb1a48c,map:TX.rock,roughness:1})));rock.position.z=-2;rock.castShadow=rock.receiveShadow=true;g.add(rock);const dark=new T3.Mesh(new T3.PlaneGeometry(2,2.6),new T3.MeshBasicMaterial({color:0x100f0c}));dark.position.set(0,1.25,-.12);g.add(dark);cb(g,1.8,.04,2.8,0x594f3b,0,.015,-.4);for(const x of [-1.3,1.3]){cb(g,.08,.95,.08,0x4d3725,x,.48,.7);cm(g,new T3.ConeGeometry(.12,.25,7),0xffaf45,x,1,.7)} };

// Selecting another unit always exits Ariel's one-shot building target mode.
const settlementSelect=setSel;
setSel=function(ids,...args){if(blessingMode&&!(ids.length===1&&byId.get(ids[0])?.type==='ariel'))blessingMode=false;return settlementSelect(ids,...args)};
const compactHudStyle=document.createElement('style');compactHudStyle.textContent=`
#memory-hud{left:8px;width:210px;max-width:calc(100vw - 32px);padding:6px 8px;font:11px/1.3 sans-serif;background:#132a2dc9;border-radius:4px}
#memory-hud b{display:inline;font-size:11px}#memory-age,#blessing-state{display:none}#memory-objective{margin:4px 0;max-height:44px;overflow:auto}#memory-hud button{padding:4px 6px;margin-top:2px;font-size:10px}#obj{display:none!important}
#memory-hud.folded #memory-objective,#memory-hud.folded #bless-building,#memory-hud.folded #mission-action{display:none!important}
#memory-hud.folded #mission-guide{display:none!important}
#memory-hud #fold-objective{float:right;margin:0 0 0 5px;padding:1px 5px;font-size:11px;border:0;background:transparent}
#modal.patron-modal .card{display:grid!important;grid-template-columns:minmax(0,.9fr) minmax(0,1.1fr);gap:18px;max-width:900px!important;padding:12px!important;background:#132324;align-items:stretch}
#modal.patron-modal #story-visual{display:flex!important;flex-direction:column;min-height:0;margin:0;overflow:hidden;border:1px solid #8f7142;background:#162222}
#modal.patron-modal #scene{display:none!important}
#modal.patron-modal #story-art{display:block!important;width:100%;height:100%;min-height:355px;flex:1;object-fit:cover;object-position:31% center;aspect-ratio:auto;border:0}
#modal.patron-modal #story-caption{display:block!important;border:0;border-top:1px solid #856b42;background:#182b29;color:#e6d6aa;font:12px/1.35 Georgia,serif;padding:9px 11px}
#modal.patron-modal .body{align-content:center;gap:9px;padding:10px 8px 10px 0}
#modal.patron-modal #m-eb{color:#d2ac6f;font-size:11px;letter-spacing:.23em}
#modal.patron-modal #m-title{font:clamp(26px,3.2vw,39px)/1.08 Georgia,serif;color:#f5d793}
#modal.patron-modal #m-text{color:#cad9cf;font:14px/1.4 sans-serif}
#modal.patron-modal #m-acts{display:grid;grid-template-columns:1fr;gap:8px;margin-top:5px}
#modal.patron-modal .patron-choice{display:grid;grid-template-columns:38px 1fr 18px;align-items:center;gap:10px;text-align:left;width:100%;min-height:72px;padding:9px 12px;border:1px solid #786746;background:linear-gradient(110deg,#27413d,#1a302f 70%);color:#f5e7c5;box-shadow:inset 3px 0 #b99251;cursor:pointer;transition:background .15s,transform .15s}
#modal.patron-modal .patron-choice:hover,#modal.patron-modal .patron-choice:focus-visible{background:linear-gradient(110deg,#385a52,#264540);transform:translateX(2px);outline:2px solid #e0bd74;outline-offset:1px}
#modal.patron-modal .patron-number{display:grid;place-items:center;width:34px;height:34px;border:1px solid #a98c5a;border-radius:50%;color:#ead09a;font:17px Georgia,serif}
#modal.patron-modal .patron-copy{display:grid;gap:2px}.patron-copy strong{font:18px Georgia,serif}.patron-copy small{font:12px/1.3 sans-serif;color:#c9d7ca}.patron-arrow{font:28px Georgia,serif;color:#deb973}
@media(max-width:620px){#modal.patron-modal .card{grid-template-columns:1fr;gap:10px}#modal.patron-modal #story-visual{max-height:160px}#modal.patron-modal #story-art{min-height:130px}#modal.patron-modal #story-caption{display:none!important}#modal.patron-modal .body{padding:0 3px 4px}#modal.patron-modal .patron-choice{min-height:56px;padding:6px 9px}#modal.patron-modal .patron-copy strong{font-size:16px}}
`;document.head.append(compactHudStyle);const foldObjective=document.createElement('button');foldObjective.id='fold-objective';foldObjective.textContent='−';foldObjective.title='Collapse mission panel';foldObjective.setAttribute('aria-label','Collapse mission panel');$('#memory-hud').prepend(foldObjective);foldObjective.onclick=()=>{const folded=$('#memory-hud').classList.toggle('folded');foldObjective.textContent=folded?'+':'−';foldObjective.setAttribute('aria-label',folded?'Expand mission panel':'Collapse mission panel')};
const missionGuide=document.createElement('button');missionGuide.id='mission-guide';missionGuide.hidden=true;$('#memory-objective').after(missionGuide);
const plainMissionHUD=refreshMissionHUD;
refreshMissionHUD=function(){plainMissionHUD();if(!memory||!campaignActive)return;const s=PLANS[memory.id][memory.stage],guide=$('#mission-guide'),objective=$('#memory-objective');guide.hidden=true;if(s?.kind==='siamak'){objective.textContent=memory.duelStarted?'At the northern pass: Siamak is fighting the Black Demon. Watch the encounter.':'Send Prince Siamak to the gold mission marker at the northern pass.';guide.textContent='Find Prince Siamak';guide.hidden=!!memory.duelStarted;guide.onclick=()=>{const prince=byId.get(memory.siamakId);if(prince&&alive(prince)){setSel([prince.id]);centerOn(prince.x,prince.y)}}}else if(memory.id===2&&s?.kind==='build'&&s.type==='blacksmith'){if(age<2){const need=Math.max(0,AGEUP.cost.gold-res.gold);objective.textContent=ageQueued()?'Blacksmith workshop unlocks when the Town Center finishes advancing to the Age of Iron.':'Blacksmith is a building. Build a Fire Temple, gather '+need+' more gold, then advance at the Town Center to the Age of Iron.';guide.textContent='See Age of Iron';guide.onclick=()=>{const tc=ents.find(e=>e.type==='tc'&&e.team===0&&e.done&&alive(e));if(tc){setSel([tc.id]);centerOn(tc.x,tc.y);showUpgrade('ageup')}else msg('Build a Town Center to advance.','warn')}}else{objective.textContent='Build a Blacksmith workshop: select a villager, choose Blacksmith, then click clear ground. Cost: 150 wood and 80 gold.';guide.textContent='Place Blacksmith';guide.onclick=()=>{const v=ents.find(e=>e.type==='villager'&&e.team===0&&alive(e));if(!v){msg('Train a villager at the Town Center first.','warn');return}setSel([v.id]);centerOn(v.x,v.y);if(afford(DEF.blacksmith.cost))doAct('build:blacksmith');else msg('Blacksmith needs '+costLong(DEF.blacksmith.cost)+'.','warn')}}guide.hidden=false}}
const plainResumeMemory=resumeMemory;
resumeMemory=async function(){const saved=readSave();if(!saved||landscapeBusy)return;landscapeBusy=true;try{await prepareLandscape(saved.memory.id);plainResumeMemory();if(!memory||!campaignActive)return;if(memory.id>1&&!ents.some(e=>LANDSCAPE_TYPES.has(e.type))){addLandscapeForms(memory.id);saveMemory(false)}if(PLANS[memory.id]?.[memory.stage]?.kind==='siamak'){if(memory.duelResolved)showSiamakAftermath();else if(!memory.marker)beginStage();else refreshMissionHUD()}}finally{landscapeBusy=false}};
$('#resume-memory').onclick=resumeMemory;
// Weathered ridge surfaces, with several summits and irregular, tapered foothills.
BUILD.mountain=g=>{const nx=72,nz=40,pos=[],cols=[],idx=[],uv=[];for(let z=0;z<=nz;z++)for(let x=0;x<=nx;x++){const u=x/nx,v=z/nz,px=u*16-8,pz=v*8-4;const rim=Math.pow(Math.max(0,Math.sin(Math.PI*u)*Math.sin(Math.PI*v)),1.15);const spine=5.4+1.6*Math.sin(px*.65)+.8*Math.cos(px*1.45+pz*.4);const crags=.35*Math.sin(px*4.1+pz*2.6)+.2*Math.sin(px*7-pz*5);const h=Math.max(0,rim*(spine+crags));pos.push(px,h,pz);uv.push(u*3,v*2);const c=new T3.Color().setRGB(.27+h*.012,.245+h*.01,.20+h*.009);const strata=.93+.07*Math.sin(h*12+px*.5);c.multiplyScalar(strata);cols.push(c.r,c.g,c.b)}for(let z=0;z<nz;z++)for(let x=0;x<nx;x++){const i=z*(nx+1)+x;idx.push(i,i+nx+1,i+1,i+1,i+nx+1,i+nx+2)}const geo=new T3.BufferGeometry();geo.setAttribute('position',new T3.Float32BufferAttribute(pos,3));geo.setAttribute('color',new T3.Float32BufferAttribute(cols,3));geo.setAttribute('uv',new T3.Float32BufferAttribute(uv,2));geo.setIndex(idx);geo.computeVertexNormals();const rock=new T3.Mesh(geo,patch(new T3.MeshStandardMaterial({vertexColors:true,map:TX.rock,roughness:1})));rock.castShadow=rock.receiveShadow=true;g.add(rock);for(let i=0;i<18;i++){const x=Math.sin(i*13.7)*7,z=Math.cos(i*4.9)*3.5;const r=cm(g,new T3.DodecahedronGeometry(.18+(i%4)*.09,1),0x817c69,x,.1,z);r.scale.y=.65;}};
BUILD.ridge=g=>{for(const [x,z,h,r] of [[-.68,-.25,1.45,.8],[.35,-.48,2.2,.85],[.82,.55,1.18,.64],[-.55,.7,.8,.6]]){const rock=cm(g,new T3.DodecahedronGeometry(1,1),0x786f64,x,h*.39,z);rock.scale.set(r,h*.55,r*.8)}for(let i=0;i<7;i++){const x=Math.sin(i*2.9)*1.15,z=Math.cos(i*4.1)*1.08;const stone=cm(g,new T3.DodecahedronGeometry(.18+i%3*.06,0),0xaaa08a,x,.13,z);stone.scale.y=.55}};
BUILD.mesa=g=>{cm(g,new T3.CylinderGeometry(1.15,1.4,.46,7),0xa78968,0,.25,0);cm(g,new T3.CylinderGeometry(.91,1.17,.8,7),0xa17d5b,-.1,.78,-.1);cm(g,new T3.CylinderGeometry(.98,.99,.23,7),0xb69770,-.1,1.26,-.1);for(let i=0;i<5;i++){const a=i*2.7;const rock=cm(g,new T3.DodecahedronGeometry(.25+i%2*.1,0),0x8a745d,Math.cos(a)*1.1,.13,Math.sin(a)*1.1);rock.scale.y=.55}};
BUILD.copse=g=>{for(const [x,z,h] of [[-.8,-.6,2.2],[.65,-.72,2.65],[-.1,.65,1.8],[1,.55,1.4]]){cm(g,new T3.CylinderGeometry(.085,.12,h*.6,7),0x70523a,x,h*.3,z);const crown=cm(g,new T3.ConeGeometry(.4,h*.8,9),0x345c3f,x,h*.66,z);crown.scale.z=.9}for(let i=0;i<8;i++)cm(g,new T3.DodecahedronGeometry(.17,0),0x5f7452,Math.sin(i*7.1)*1.15,.1,Math.cos(i*5.2)*1.15)};
BUILD.stonefield=g=>{for(let i=0;i<11;i++){const a=i*2.43,r=.3+(i%4)*.31,x=Math.cos(a)*r,z=Math.sin(a)*r,s=.2+(i%5)*.09;const rock=cm(g,new T3.DodecahedronGeometry(s,0),i%3?0x948776:0xb0a38c,x,s*.43,z);rock.scale.set(1.1,.55,1.3)}};
BUILD.snowcrest=g=>{BUILD.ridge(g);for(const [x,y,z,r] of [[.35,1.8,-.48,.58],[-.68,1.15,-.25,.4],[.82,.9,.55,.35]]){const snow=cm(g,new T3.ConeGeometry(r,.38,7),0xdde4df,x,y,z);snow.rotation.y=.3}};

const slimTop=document.createElement('style');slimTop.textContent=`
:root{--bar:38px}
#top{height:38px!important;min-height:0;display:flex!important;flex-wrap:nowrap;gap:6px;padding:3px 7px;left:5px;right:5px;top:5px;border-width:1px;box-sizing:border-box;background:#172725ed;overflow-x:auto}
#top::before{display:none}#top .res{font-size:12px;gap:3px;flex:none}#top .res svg,#top .res img{width:15px;height:15px}
#top #age{font:12px Georgia,serif;margin-left:auto;max-width:none;white-space:nowrap;flex:none;padding:4px 6px;letter-spacing:0}
#top .tb{min-height:0;height:27px;padding:3px 6px;font-size:10px;flex:none;grid-column:auto}
#top .unit-shortcut{display:flex;flex-direction:row;min-height:0;gap:0}#top .unit-shortcut small{display:none}#top .unit-shortcut strong{font-size:10px;white-space:nowrap}
#top #clock{font-size:10px;flex:none}#top #b-menu{font-size:10px}
@media(max-width:620px){#top{gap:4px;height:34px!important}#top .res{font-size:11px}#top #age{font-size:10px}#top .tb{padding:2px 4px}#top #clock{display:none}}
`;document.head.append(slimTop);$('#b-idle strong').textContent='Idle workers';$('#b-army strong').textContent='Army';$('#b-hero strong').textContent='Heroes';
